### ISSUE TITLE
Polymorphism for Embedded classes

### ISSUE THREAD

**Issue by stickfigure** [objectify/objectify#157]
Original [issue 142](https://code.google.com/p/objectify-appengine/issues/detail?id=142) created by objectify on 2012-12-28T03:23:03.000Z:

<b>What steps will reproduce the problem?</b>
1. We find the polymorphism through @Entity/@SubClass very powerful for purposes of customization of object model for specific customer installations.  However, it does not support the @Embedded classes, and having new @Embedded class in the SubClass with the same variable name, it complains and does not register.
What is the solution to overcome this currently?  

Do you have plans to support it for the embedded classes as well?

<b>2.</b>
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>

<b>What version of the product are you using? On what operating system?</b>

<b>Please provide any additional information below.</b>

**Comment by tj-recess** [comment]
Could you provide an example of this? 
My use case is same http://stackoverflow.com/questions/5278717/polymorphism-with-objectify but I'm getting InstantiationException for interface/Abstract class (same as what's mentioned in link).
