### ISSUE TITLE
Remote API seems not to work in Objectify 4

### ISSUE THREAD

**Issue by stickfigure** [objectify/objectify#160]
Original [issue 145](https://code.google.com/p/objectify-appengine/issues/detail?id=145) created by objectify on 2013-02-02T14:14:04.000Z:

<b>What steps will reproduce the problem?</b>
1. Deploy GAE application with RemoteAPI servlet handler
2. Deploy or run locally second GAE application
3. Try to fetch remote data running the following snippet of code:

static {
   ObjectifyService.register(Item.class);
}

public void doGet(HttpServletRequest req, HttpServletResponse resp) throws IOException {
   RemoteApiOptions options = new RemoteApiOptions().server(appId, 443).credentials(username, password);

   installer = new RemoteApiInstaller();
   installer.install(options);

   Key&lt;Item&gt; itemKey =  Key.create(Item.class, itemId);

   //item is null, despite it is present is remote datastore
   Item item = ofy().load().key(itemKey ).getValue();

   com.google.appengine.api.datastore.Key itemRawKey = itemKey.getRaw();

   Consistency consistency = Consistency.STRONG;
   DatastoreServiceConfig cfg = DatastoreServiceConfig.Builder.withReadPolicy(new ReadPolicy(consistency));  
   AsyncDatastoreService datastoreService = DatastoreServiceFactory.getAsyncDatastoreService(cfg);

   //entity is non-null as expected
   Entity entity = datastoreService.get(itemRawKey).get();
}

<b>What is the expected output? What do you see instead?</b>
   Entity loaded via objectify is null despite the same query via low-level API works as expected.

<b>What version of the product are you using? On what operating system?</b>
- objectify-4.0b1
- AppEngine SDK 1.7.4
- Windows 8 x64

<b>Please provide any additional information below.</b>
- Registering entity at the moment RemoteApiInstaller has been already installed doesn't help
- The code above doesn't work both locally and deployed

**Comment by Ajeet-Meena** [comment]
@stickfigure I am facing the same issue using remotely with objectify. Is there any workaround except using filterKey() because get by id is not working?

**Comment by stickfigure** [comment]
It is very improbable that the remote api is somehow preventing get-by-id from working - and I've used the Remote API to thoroughly abuse Objectify and the low level API. This issue was never sufficiently explained and I probably should have closed it years ago.

That said, I'm willing to help you debug your issue. Pretend for a moment that this issue does not exist. Start from scratch and explain what you're seeing in detail, without jumping to conclusions as to the cause (like "the remote api is broken"*).

* There are a couple ways in which the remote api is broken, but get-by-key isn't one of them.

**Comment by Ajeet-Meena** [comment]
First, Thanks Jeff for replying.

I am able to connect deployment datastore using remotely on local by using the following way:

```
// Inside ServletContextListener in contextInitialized() to set custom ObjectifyFactory
ObjectifyService.setFactory(new ObjectifyFactoryLocal());
```

This is how my ObjectifyFactory looks like:
```
public class ObjectifyFactoryLocal extends ObjectifyFactory {

    private final Remotely remotely;

    public ObjectifyFactoryLocal() {

        RemoteApiOptions options = new RemoteApiOptions()
                .server("xyz.appspot.com", 443)
                .useApplicationDefaultCredential();

        remotely = new Remotely(options, new RemoteCheck() {
            public boolean isRemote(String namespace) {
                return true;
            }
        });

    }

    @Override
    protected AsyncDatastoreService createRawAsyncDatastoreService(DatastoreServiceConfig cfg) {
        AsyncDatastoreService raw = super.createRawAsyncDatastoreService(cfg);
        return remotely.intercept(raw);
    }
}
```
I added required servlet in web.xml:

```
 <servlet>
        <display-name>Remote API Servlet</display-name>
        <servlet-name>RemoteApiServlet</servlet-name>
        <servlet-class>com.google.apphosting.utils.remoteapi.RemoteApiServlet</servlet-class>
        <load-on-startup>1</load-on-startup>
    </servlet>
    <servlet-mapping>
        <servlet-name>RemoteApiServlet</servlet-name>
        <url-pattern>/remote_api</url-pattern>
    </servlet-mapping>
```

My list APIs are working fine but the bellow one is returning null:
`Job job = ofy().load().type(Job.class).id(id).now();`

**Comment by Ajeet-Meena** [comment]
Hi, @stickfigure. Can you please help us resolve this issue it is getting a roadblock for us.

**Comment by elliotcerd-m** [comment]
Hi @Ajeet-Meena 
On which jar, can I get Remotely class? 
I'm having a lot of issues to make objectify work along with Remote api, even though Remote Api itself it's working fine.
Currently I'm getting error: 
`com.google.cloud.datastore.DatastoreException: Unauthenticated. at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.translate(HttpDatastoreRpc.java:128) at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.translate(HttpDatastoreRpc.java:113) at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.lookup(HttpDatastoreRpc.java:163) at com.google.cloud.datastore.DatastoreImpl$3.call(DatastoreImpl.java:392) at com.google.cloud.datastore.DatastoreImpl$3.call(DatastoreImpl.java:389) `

My goal is to access to remote datastore from K8's running also on GCP.

Thanks!
