### ISSUE TITLE
MemcacheService should be replaced with AsyncMemcacheService with timeout on get request

### ISSUE THREAD

**Issue by stickfigure** [objectify/objectify#197]
Original [issue 183](https://code.google.com/p/objectify-appengine/issues/detail?id=183) created by objectify on 2013-12-18T13:05:05.000Z:

<b>What steps will reproduce the problem?</b>
1. wait for bad day at Google, when memcache service will work but it will work extremly slow
2. try to do get of cached entity, it will take up to 3s for single get, because of slow request to memcache

<b>What is the expected output? What do you see instead?</b>
Expected behaviour should be fallback after x ms (100-200ms) of memcache not returning anything back to requesting datastore. Instead we wait for 3s or even more to get single entity.

<b>What version of the product are you using? On what operating system?</b>
We are using objectify 3 and also 4, same problem. Problem accures only on Google App Engine when their memcache is working slow.

MemcacheService should be replaced with AsyncMemcacheService which offeres get with timeout, like this:

AsyncMemcacheService service = MemcacheServiceFactory.getAsyncMemcacheService();
if (service != null) {
        try {
                Future&lt;Object&gt; response = service.get(key);
                return response.get(500, TimeUnit.MILLISECONDS);
         } catch (InvalidValueException ive) {
                log.warning(&quot;Serialization error: \n&quot; + ive.getMessage());
                return null;
         } catch (MemcacheServiceException | InterruptedException | ExecutionException | TimeoutException e) {
                log.warning(&quot;MemcacheServiceException: &quot; + e.getMessage());
                return null;
         }
 }

**Comment by knitterb-razzle** [comment]
We ran into this issue yesterday where Google's memcache service was responding extremely slowly and we ended up with requests that took more than 60s (hit deadline exceeded exceptions).  Would be great if there was either a default timeout, configurable timeout, or a global way to easily turn off caching when this happens.

**Comment by rmaclean-ee** [comment]
any progress or workarounds for this?

**Comment by stickfigure** [comment]
The code in v6 is significantly changed. It should be possible to configure timeouts more easily. If there are still issues I will reopen this.
