### ISSUE TITLE
Provide the feature of Query.CompositeFilter

### ISSUE THREAD

**Issue by stickfigure** [objectify/objectify#200]
Original [issue 186](https://code.google.com/p/objectify-appengine/issues/detail?id=186) created by objectify on 2013-12-18T15:42:52.000Z:

According to documentation, Query.addFilter() and Query.getFilterPredicates() are deprecated.

Query.CompositeFilter should be used, with Query.CompositeFilterOperator.AND.

Also, Query.setFilter() should be visible on the objectify query interface,
so one could use Query.CompositeFilterOperator.OR

Writing a wrapper around CompositeFilter, just to have one, is a bit pointless, and defining complex filters via the standard builder pattern would a bit confusing and ugly, because you don't have operator precedence and associativity, so a simple setFilter function on the objectify query interface seems to be the best solution.

use case: ((id=1 OR id=2343 or id=3) AND someproperty=3)

version: 4.0rc2

**Comment by stickfigure** [comment]
This has been committed in a branch. OR support is not yet in the google-cloud-datastore library however. It's coming soon.

**Comment by nbartels** [comment]
OR support is part of the google-cloud-datatstore lib with since version 2.14.0:
https://github.com/googleapis/java-datastore/releases/tag/v2.14.0
https://github.com/googleapis/java-datastore/commit/99b784332919ccc813a94ba17beaaa11b02b1c8e

**Comment by stickfigure** [comment]
This is supported by Objectify 6.1.0+
