### ISSUE TITLE
Support Datastore on GCE instances and other platforms.

### ISSUE THREAD

**Issue by stickfigure** [objectify/objectify#203]
Original [issue 189](https://code.google.com/p/objectify-appengine/issues/detail?id=189) created by objectify on 2014-01-13T17:30:23.000Z:

The App Engine Datastore has been expanded to run on other platforms. (https://developers.google.com/datastore/docs/activate)

The most interesting and obvious new alternative is running on Google Compute Engine instances, but other platforms are supported as well. It would be great if Objectify was supported everywhere the datastore was.

**Comment by fkorotkov** [comment]
Will it make sense to move objectify to use [google-cloud](http://googlecloudplatform.github.io/google-cloud-java/0.3.0/index.html) library(comment 2)? Do I understand correctly that it's the only way at the moment to make objectify work anywhere?

**Comment by fabiofalci** [comment]
Yeah, I'm interested on this as well.
Trying to use datastore/objectify on Container Engine.

Datastore seems to be working well using google-cloud but not objectify.

Is this a big job? Can we help in any way?

**Comment by stickfigure** [comment]
I spent some time looking into it a while ago - It's a pretty major effort. It's a whole new API, although fairly similar to the old one. You could probably implement an adaptor at the DatastoreService/AsyncDatastoreService layer, although converting the key types would be annoying.

Keep in mind that there is no public REST API to the task queue (at least not yet). So you wouldn't be able to transactionally enqueue tasks. That's a pretty serious limitation, and why I don't consider this new API ready for prime-time.

**Comment by fabiofalci** [comment]
Cool, good to know, thanks @stickfigure

**Comment by muzuro** [comment]
Hi curious to know current status, is it still not work at compute engine/kubernetes engine?

**Comment by stickfigure** [comment]
Versio 6.0a1 has been released, which uses the new Cloud SDK and works from anywhere. See here:

https://github.com/objectify/objectify/wiki/UpgradeVersion5ToVersion6

Try it out - but keep in mind that while the test suite is green, this is the first alpha release and there may be issues.  Not recommended for production yet. Feedback will be helpful.

**Comment by stickfigure** [comment]
Closing this as done.
