### ISSUE TITLE
result of ofy().cache(true).consistency(STRONG).load().key(k).now() is inconsistent

### ISSUE THREAD

**Issue by stickfigure** [objectify/objectify#224]
Original [issue 210](https://code.google.com/p/objectify-appengine/issues/detail?id=210) created by objectify on 2014-06-19T14:14:25.000Z:

I noticed that entities were not always consistently retrieved.  Fields that were set yesterday sometimes were retrieved empty and sometimes have the correct values in them.  I just retrieved one particular entity 8 times -- half the time it had the new value, half the time it did not.

I then tried: ofy().cache(false).consistency(STRONG).load().key(k).now()
8 times in succession and it retrieved the correct values every time.

I then tried: ofy().cache(true).load().key(k).now() 8 times in succession -- it retrieved the correct values every time.

The values are properly filled in when I look at the object in the GAE datastore viewer.  The implementation is an applet with virtually all code server-side (i.e., no logic other than user-interaction resident on the client).

I am using the following:
  1) GAE SDK 1.9.6
  2) Objectify 5.0.2
  3) Running using Java JDK 1.7.0_55

I am beginning to wonder if there is a problem in the GAE datastore itself.  The problem does not seem to occur in the GAE development server (but it's hard to tell because of the small dataset size that one can readily use in the development server).

Although I believe I have found the problem and resolved it by removing call to &quot;.consistency(STRONG)&quot;, it should probably be resolved in Objectify so that some other newbie (like I am) doesn't inadvertently trigger the problem.

Thanks,
Tony

**Comment by juanjoitc** [comment]
Hello... 

I'm having the same problem, I found this [post](http://stackoverflow.com/questions/28733992/how-properly-store-and-query-an-objectify-entity-with-ancestor), which gives a partial solution, using google datastore API get to retrieve the correct information.

is there any way to solve this using Objectify? I really don't want to use the native get() which returns and Entity, instead of my own class.

Cheers.

Juanjo

**Comment by CristianKrieger** [comment]
I am facing this exact issue as well. It took us by surprise when it appeared, one day the server was running smoothly; the other, it starts to behave erratically. Our users are really upset about this bug, and we haven't found a solution or workaround. I noticed no one has been assigned this defect, are there any plans to solve it?

**Comment by stickfigure** [comment]
You are all mistaken. Look your own code over or seek assistance in stackoverflow or the Google Group.

This is an invalid bug. The default for consistency() *is* STRONG; `ofy().consistency(Consistency.STRONG)` is a no-op.

@juanjoitc Your problem is that you are comparing a filtered query (which is eventually consistent) with a get-by-key (which is strongly consistent by default). Apples and oranges.

@CristianKrieger there's not enough information in your post to answer.

Please use the Google Group for support.
