### ISSUE TITLE
ClassCastException: com.google.appengine.api.datastore.Entity cannot be cast to XXX

### ISSUE THREAD

**Issue by stickfigure** [objectify/objectify#225]
Original [issue 211](https://code.google.com/p/objectify-appengine/issues/detail?id=211) created by objectify on 2014-06-22T13:06:06.000Z:

<b>What steps will reproduce the problem?</b>

I recently added a new entity to my project with 2 fields :
@Id String id
@Serialize Serializable value

When calling ObjectifyService.ofy().load().type(XXX.class).id(id).now();
from time to time I got the exception
java.lang.ClassCastException: com.google.appengine.api.datastore.Entity cannot be cast to XXX

The exception is not so frequent but when it occurs on a specific entity, then it repeats multiple times for that entity.

<b>What version of the product are you using? On what operating system?</b>

Objectify 5.0.3
Also got the problem with Objectify 4.0rc2, that's why I updated.

**Comment by inewland53** [comment]
Had a similar issue and calling `ObjectifyService.register(MyClass.class);` solved the issue. Thanks!
