### ISSUE TITLE
Support ID and name on the same kind

### ISSUE THREAD

**Issue by stickfigure** [objectify/objectify#236]
Original [issue 222](https://code.google.com/p/objectify-appengine/issues/detail?id=222) created by objectify on 2014-10-24T10:59:05.000Z:

There may be cases where some of the entities of a kind have numeric ID and other have a string name (probably most relevant during migration), which make it impossible to use with Objectify. I propose changing Objectify to behave as follows:
- If @Id is present on a String property and it is null when saving - act as if it was Long - use the datastore ID generation.
- If @Id is present on a String property and the loaded entity has a numeric ID, set the property to the ID's toString() value.

**Comment by GabiAxel** [comment]
Since it's been more than a year since I suggested this, and no one, including myself, seems to express any interest in it, I suggest closing this issue.

**Comment by stickfigure** [comment]
There's a legitimate need represented here, but I think the wrong approach described. The right answer is the solution in https://github.com/objectify/objectify/issues/257

I can't promise when it will be done, but it should be kept open until it is.
