### ISSUE TITLE
Objectify automatically uses hybrid queries when it cannot

### ISSUE THREAD

**Issue by stickfigure** [objectify/objectify#248]
Original [issue 234](https://code.google.com/p/objectify-appengine/issues/detail?id=234) created by objectify on 2015-04-03T16:56:54.000Z:

I'm using Objectify v5.1.5 and am attempting to run a query that uses an &quot;in&quot; query along with an orderBy clause.

SELECT \* FROM MyEntity WHERE someProperty IN ( 'value1', 'value2') ORDER BY some.other.property DESC

This produces the following error on my system:

&quot;The provided keys-only multi-query needs to perform some sorting in memory.  As a result, this query can only be sorted by the key property as this is the only property that is available in memory.&quot;

Which would make since if I was using a keys only query. However I am not attempting to use a keys only query. After some digging around and enabling the &quot;FINEST&quot; logging, I found the following:

FINEST com.googlecode.objectify.impl.QueryEngine queryHybrid: Starting hybrid query

Objectify is enabling a hybrid query which automatically converts the query to a keys only query, thus the error. 

We just recently converted from objectify 4 to 5 and that conversion is what caused this error. I noticed that Objectify 4 and 5 handles the logic to use a hybrid query differently.

The following is how objectify 4 decides this should be a hybrid query. Notice the &quot;hasMulti &amp;&amp; hasNonKeyOrder&quot; makes the query non-hybrid.

https://code.google.com/p/objectify-appengine/source/browse/src/main/java/com/googlecode/objectify/impl/QueryImpl.java?name=v4

/*\* Produces the basic iterable on results based on the current query.  Used to generate other iterables via transformation. */
        private QueryResultIterable&lt;T&gt; resultIterable() {
                boolean hybridize = hybrid;

```
            if (!hasExplicitHybrid) {
                    // These are the special conditions we know about.  It may expand.

                    if (hasMulti &amp;&amp; hasNonKeyOrder)
                            hybridize = false;
            }

            if (hybridize)
                    return loader.createQueryEngine().queryHybrid(this.getActualQuery(), this.fetchOptions());
            else
                    return loader.createQueryEngine().queryNormal(this.getActualQuery(), this.fetchOptions());
    }
```

The following is how objectify 5 decides if the query should be a hybrid query. This is basically saying that if caching is enabled, do a hybrid query. No check for multi queries with sort orders by a property.

https://code.google.com/p/objectify-appengine/source/browse/src/main/java/com/googlecode/objectify/impl/QueryImpl.java?name=master

/*\* Produces the basic iterable on results based on the current query.  Used to generate other iterables via transformation. */
        private QueryResultIterable&lt;T&gt; resultIterable() {
                if (!actual.getProjections().isEmpty())
                        return loader.createQueryEngine().queryProjection(this.getActualQuery(), this.fetchOptions());
                else if (shouldHybridize())
                        return loader.createQueryEngine().queryHybrid(this.getActualQuery(), this.fetchOptions());
                else
                        return loader.createQueryEngine().queryNormal(this.getActualQuery(), this.fetchOptions());
        }

 /**
         \* @return true if we should hybridize this query
         */
        private boolean shouldHybridize() {
                if (hybrid != null)
                        return hybrid;

```
            // If the class is cacheable
            if (classRestriction != null &amp;&amp; loader.getObjectifyImpl().getCache() &amp;&amp; fact().getMetadata(classRestriction).getCacheExpirySeconds() != null)
                    return true;

            return false;
    }
```

Objectify should recognize when a hybrid query is not appropriate and use a normal query instead.

**Comment by hilkeheremans** [comment]
We are experiencing exactly the same issue.

**Comment by seahrh** [comment]
Same issue on 5.1.10. Is there a workaround in the interim, such as an option to force non-hybrid query?

**Comment by tj-recess** [comment]
+1. Workaround is to use ```hybrid(false)``` in query.
However, I'm facing a cursor issue with such queries. Even though ```iterator.hasNext()``` is true, ```iterator.getCursor()``` returns null.

**Comment by tj-recess** [comment]
Looks like the issue I mentioned above is here: <http://stackoverflow.com/questions/19917217/gae-cursors-not-working-on-queries-using-in-whats-the-workaround> 
Consider throwing an ```UnsupportedOperationException``` with proper error message or add this information to wiki.

**Comment by stickfigure** [comment]
Closing this due to age. If this is still an issue, we can reopen it.
