### ISSUE TITLE
Load subclasses by ID/key should filter by discriminator

### ISSUE THREAD

**Issue by GabiAxel** [objectify/objectify#254]
When fetching by type+ID or key, Objectify only takes the entity kind from the type, and ignores the discriminator in case of subclasses. This means that attempting to fetch a specific subtype can actually fetch a sibling of that subtype, and cause ClassCastException later in the code.
I propose that in case of subtypes, the default behaviour of fetching by ID/key would be to add a filter for the discriminator.

**Comment by stickfigure** [comment]
This is not possible without major redesign of keys, and probably not desirable anyways. Key<?>s are wrappers for native keys, which only store 'kind', no subclass-related information. So the information to do extra filtering does not exist. Furthermore, the CCE gives you notice that you did something dumb (loaded the wrong type), whereas simply returning null would appear to be broken behavior ("where's my data?"). We already get plenty of "where's my data?" help requests from people who forget to index fields; this would be even more obscure.
