### ISSUE TITLE
Integration with Google Search API

### ISSUE THREAD

**Issue by kishaningithub** [objectify/objectify#259]
Full Text search and Nearby places search has become a very 
necessary and common feature for apps.. It would be nice if 
objectify seamlessly integrates with google's search api :-)

**Comment by kishaningithub** [comment]
I also saw another project https://github.com/marcosvidolin/doco both should integrate and work seamlessly

**Comment by jschoedt** [comment]
+1 It is also not trivial to keep the search documents in sync and failure safe. It would be nice to have this taken care of by eg. annotations.

Some inspiration: http://sookocheff.com/post/appengine/syncing-search-documents-with-datastore-entities/
