### ISSUE TITLE
JPA Attribute Converter alike

### ISSUE THREAD

**Issue by NicolaSpreafico** [objectify/objectify#264]
Hello,
is there in Objectify something like the JPA Attribute Converter?

I have an object which is not supported by the Datastore itself (it is a custom data type) but I don't want to embed it, I want to convert it to a simple type (like String perhaps) and then convert it back during the GET flow.

For better understanding, this procedure should be placed between the conversione from Java Pojo and Entity object, and viceversa.

PUT: Pojo --> [Attribute Converter] --> Entity
GET: Entity --> [Attribute Converter] --> Pojo

I already know about the callbacks https://github.com/objectify/objectify/wiki/LifecycleCallbacks but because I don't have the entity object (but only the Pojo itself) my problem cannot be solved with this procedure. I can't stay at Pojo level because the conversion of the field change the data-type so I cannot edit the Java variable.

I seen this topic: http://stackoverflow.com/a/24441125 which seems to partially answer to my problem because is avoiding using the native "save" method of Ofy and then manage the persistence with the native API (It use Ofy only for the conversion from Pojo from Entity, not the persistence flow).

The AttributeConverter flow is very clean because it only needs an annotation on the field (and the converter implementation of course) and the all the code is managed under the hood.

If this is not already available I'd like to introduce it at a feature suggestion. 

Thanks
Regards

**Comment by stickfigure** [comment]
This feature is already present - it's actually how Objectify works internally. Look at `Translator` and `TranslatorFactory` and all the various subclasses of `TranslatorFactory`.

You can register factories before registration time. You can also annotate your fields with the `@Translate` annotation.

**Comment by NicolaSpreafico** [comment]
Thank you for the inside.
Is there any tutorial available related to the Translator?

I only found the related JavaDoc: https://objectify-appengine.googlecode.com/svn/trunk/javadoc/com/googlecode/objectify/impl/translate/package-summary.html

**Comment by stickfigure** [comment]
It's all in the javadocs, but you're looking at long-obsolete javadocs. They are here:

http://www.javadoc.io/doc/com.googlecode.objectify/objectify

(and look to github for project documentation)

For implementing a Translator, look at the examples in the project. Start with a simple value-type one like this:  https://github.com/objectify/objectify/blob/master/src/main/java/com/googlecode/objectify/impl/translate/URLTranslatorFactory.java

The collection ones are more complicated, but probably can be figured out. You can ask specific questions in the objectify google group and I'll help.

**Comment by NicolaSpreafico** [comment]
Without knowing about the Google Group forum I created a topic in StackOverflow: http://stackoverflow.com/questions/32119159/objectify-translator-as-jpa-attribute-converter

Do I need to create one in Google Group too?
