### ISSUE TITLE
wiki/Transactions mentions: The standard limit of 5 EGs applies to all transactions. I don't think that's the case anymore...

### ISSUE THREAD

**Issue by yoav-zibin** [objectify/objectify#265]
This page:
https://github.com/objectify/objectify/wiki/Transactions
writes:
The standard limit of 5 EGs applies to all transactions.

I looked here:
https://cloud.google.com/appengine/docs/java/datastore/transactions
but I can't find that limit mentioned anywhere.
Are you sure it still applies?

**Comment by yoav-zibin** [comment]
Definitely new limit (25!):
https://cloud.google.com/appengine/docs/java/datastore/#Java_Cross_group_transactions
which can belong either to a single entity group or (in the case of a cross-group transaction) to as many as twenty-five different entity groups.

**Comment by stickfigure** [comment]
Fixed, thanks for finding that!
