### ISSUE TITLE
Projection with a Map attribute in Objectify seems to not work

### ISSUE THREAD

**Issue by mwamedacen** [objectify/objectify#268]
The other day, I was having trouble with a quite shitty problem.

First thing first, here is my entity model:

```
@Entity
public class Lead {
    @Id
    private String url;

    @Index
    private Date dateCreated;

    @Index
    private Date lastDateModified;

    //This might hold hundreds of key-value couples
    //it's very painful to fetch the whole entity when we are only interested in one "column", knowing that there are more that 100.000 entities
    @Index
    private Map<String, Object> data = new HashMap<>(); 

    public Lead(String url) {
        this.url = url;
        this.dateCreated = new Date();
    }

    //getters and setters
}
```

If I have multiple "lead" entities with the following data maps:

```
leadA.data = [key1 -> value1A, key2 -> value2A, key3 -> value3A]
leadB.data = [key1 -> value1B, key3 -> value3B] //here key2 is missing
leadC.data = [key1 -> value1C, key2 -> value2C, key3 -> value3C]
leadD.data = [key1 -> value1D, key2 -> value2C, key3 -> value3D] //here the value of key2 is the same as for leadC
```

I would like to ask the datastore `SELECT DISTINCT `data.key2` FROM Lead`? and he should answer by the following result : `[value2A, value2C]`

So I picked the `.project()` service and tried few queries that failed.
I implemented it with the native Datastore's API and ProjectionQuery and it worked perfectly.

**Comment by stickfigure** [comment]
So much has changed since then that I'm not sure if this still applies. Closing this issue; if it resurfaces on v6 we can reopen.
