### ISSUE TITLE
Change indentation character from TAB to SPACE

### ISSUE THREAD

**Issue by eincs** [objectify/objectify#270]
In many open source project, SPACE is used for indentation character rather than TAB.
This is because a TAB could be a different number of columns depending on environment, but a space is always one column.
For example, width of TAB character is 8space in GitHub webpage, but it's 4space in Eclipse.

There are many examples that TAB character is not allowed by coding style.

- Google do not allow TAB for indentation character:
https://google.github.io/styleguide/javaguide.html#s2.3.1-whitespace-characters
- Apache HBase do not allow TAB chacter in source code:
https://github.com/apache/hbase/blob/master/hbase-checkstyle/src/main/resources/hbase/checkstyle.xml#L33
- And so on...

If you think changing TAB to 4SPACE for the Objectify is meaningful, I will send a pull request changing TAB to 4SPACE for indentation character.
Please give me any opinion.

**Comment by eincs** [comment]
FYI: Currently, there exists a file that using TAB and 4SPACE mixed as indentation character.
https://github.com/objectify/objectify/blob/master/src/main/java/com/googlecode/objectify/repackaged/gentyref/CaptureType.java

**Comment by stickfigure** [comment]
This project uses HARD tabs.
