### ISSUE TITLE
How to create instance of com.googlecode.objectify.KeyRange object to call allocateIdRange method in ObjectifyFactory class?

### ISSUE THREAD

**Issue by sasikrishna** [objectify/objectify#277]
Hi!...

We are using objectify 3.1 in our application and we want to allocate our own IDs for the entities. We found a method, allocateIdRange in ObjectifyFactory class. But to give a call to that method, we need to pass KeyRange object. In objectify 3.1 constructor of com.googlecode.objectify.KeyRange class is default and is not visible to out side of the package.

Can anyone help me to get through this?

Thank you
Sasi

**Comment by stickfigure** [comment]
Well that's unfortunate. 3.1 was released in 2011, it's time to upgrade :-/

Short of upgrading, you basically have two options:

 1) Build your own private release of 3.1.1 (or whatever you want to call it).
 2) Fake out the Java compiler by creating a KeyRangeFactory in your source tree within the com.googlecode.objectify package. It will have access to the package-protected constructor.

**Comment by sasikrishna** [comment]
Thank you Jeff
