### ISSUE TITLE
One To Many

### ISSUE THREAD

**Issue by leonardocregis** [objectify/objectify#278]
Im trying to figure out how to make it work.
I folowed the tutorial in the wiki:
One-To-Many Relationships
https://github.com/objectify/objectify/wiki/Entities

and created a project into the github with a test case , that doesnt works:
https://github.com/leonardocregis/objectfy-onetomany-sample

**Comment by stickfigure** [comment]
You don't mention what exactly fails, but I do notice that you're enabling eventual consistency for your tests which is a bad idea. Use this:

`new LocalDatastoreServiceTestConfig().setApplyAllHighRepJobPolicy()`

If you have further questions, best to post to the Objectify google group.
