### ISSUE TITLE
Preallocated ID unique within a parent?

### ISSUE THREAD

**Issue by seahrh** [objectify/objectify#280]
Both Objectify and GAE's `DatastoreService` provide a method to allocate entity ids unique within a parent:

[ObjectifyFactory#allocateId(Object parentKeyOrEntity, Class<T> clazz)](http://docs.objectify-appengine.googlecode.com/git/apidocs/com/googlecode/objectify/ObjectifyFactory.html#allocateId(java.lang.Object, java.lang.Class))

[DatastoreService#allocateIds(Key parent, java.lang.String kind, long num)](https://cloud.google.com/appengine/docs/java/javadoc/com/google/appengine/api/datastore/DatastoreService#allocateIds-com.google.appengine.api.datastore.Key-java.lang.String-long-)

When I call Objectify to allocate id within a parent, the ids are incremented - across different parents. 

The following example preallocates ids for the child entity:

Parent A has child entity id 1
Parent B has child entity id 2
Parent C has child entity id 3

But I was expecting:

Parent A has child entity id 1
Parent B has child entity id 1
Parent C has child entity id 1

Objectify 5.1.9

**Comment by stickfigure** [comment]
Triple check that you're passing in different parent keys properly. As you can see from `ObjectifyFactory.allocateId()`, it just calls through to the DatastoreService method.
