### ISSUE TITLE
OnSave method did not set entity field

### ISSUE THREAD

**Issue by seahrh** [objectify/objectify#282]
Entity field is a String, neither @Id or @Parent. The @OnSave method fired correctly. The field was set correctly in the method but the saved entity did not. 

On 5.1.10.

**Comment by stickfigure** [comment]
You will have to be a lot more specific. Got a code example? If the field was set in your onsave method, it would have been saved to the db. Something else is going on.

**Comment by seahrh** [comment]
@OnSave
    private void onSave() {
		setLastEditTime();
		audit();
	}
	
	private void setLastEditTime() {
         // do something
		if (condition) {
			lastEditTime(writeTime());
			log.info("set last edit time [{}]", lastEditTime()); // entered if block and set the field
		}
	}

I checked that execution entered the if block and set the entity's field (`lastEditTime`, a String) but this new value was not saved to the datastore.

**Comment by stickfigure** [comment]
Keep looking. This is not a bug in Objectify; there are tests for "values set in @OnSave methods get saved" and in any rate I have a dozen applications that would not work if there was such a blatant problem.

Check your code that sets the value, and check any possible code that could reset the value (say, in audit()). Check the condition. If you want help, try the Objectify mailing list or stackoverflow.
