### ISSUE TITLE
Global Cache question

### ISSUE THREAD

**Issue by mingtaozhangsc** [objectify/objectify#283]
We are writing some code to do offline write to Datastore. But we still want to leverage Global Cache to speed up reading. Currently, the write will trigger mem-cache update (instead of invalidate certain keys for next read), and we are hitting the write limit of mem-cache.

I found this in the wiki:
'You can disable the global cache for an operation:  {{{ofy().cache(false).load()...}}}'

Is it possible to disable cache during write and expect eventually consistency during read? Is there an option to say invalidate but not write-through?

**Comment by unitydynamics** [comment]
If you're using Objectify to write entities you can use `cache(false)` setting when you call `ofy().cache(false).save(...`  And then simply use `ofy().cache(true).load(...` on your read logic.

**Comment by stickfigure** [comment]
Objectify's cache is read-through, which is to say that a write clears the memcache entry and a read pulls the data into the cache. I don't know how you would avoid cache inconsistency issues if you skip the global cache during write - the cache key would not get invalidated and every subsequent read will read the stale data.

If you're willing to live with stale data, sure disable the cache for write and put a expiration on the entries. But if your read/write ratios are not cache-friendly, how about just skipping `@Cache` entirely for the entity?

**Comment by mingtaozhangsc** [comment]
Thank you :)
