### ISSUE TITLE
Strategy to support transparent ShortBlob / Blob reading?

### ISSUE THREAD

**Issue by unitydynamics** [objectify/objectify#284]
I've recently started using gcloud-java to write entities to the datastore.  It seems to automatically insert ShortBlobs when the blob size is small.  I noticed then that Objectify will fail to read the entity: `Expected class com.google.appengine.api.datastore.Blob, got class com.google.appengine.api.datastore.ShortBlob: <ShortBlob: 247 bytes>`  

Is there a good strategy that Objectify might employ to automatically read or expect ShortBlob instances?  I've also asked the gcloud-java dev community if there is a way to force writing of full Blob objects.

**Comment by stickfigure** [comment]
I'll cut a new build this afternoon that reads ShortBlob into a byte[]. That must have been added sometime more recently and I didn't notice.

**Comment by unitydynamics** [comment]
Hooray!  I test it out when I see it.  Thanks Jeff.

**Comment by stickfigure** [comment]
5.1.11 has the fix and has been uploaded to maven central

**Comment by unitydynamics** [comment]
Works like charm!  Where's the donate button?!?  Thanks again
