### ISSUE TITLE
Using outside app engine..

### ISSUE THREAD

**Issue by doggie1989** [objectify/objectify#285]

**Comment by Flo354** [comment]
I just don't understand why we cannot use AuthCredentials like in gcloud-java : http://googlecloudplatform.github.io/gcloud-java/0.2.5/ (tab run elsewhere

**Comment by doggie1989** [comment]
@Flo354 

I am now using gcloud-java outside app engine and objectify inside app engine.
The problem is I need to maintain 2 branch with same function...

**Comment by Flo354** [comment]
@doggie1989 I see. But i don't have an app-engine, and don't want to pay for it :/

**Comment by doggie1989** [comment]
I am heavily using app engine in my business...
Also I am using AWS,Linode.
For some parts of services ,they are very suitable for running on app engine...
ps:app engine is not expensive if you use it properly(cheaper than VPS)

**Comment by Flo354** [comment]
Yes, that's why I want to use Datastore. IMO, it's much much better than DynamoDB.
But, I can't switch to app engine and don't find any solution.

**Comment by willedwards** [comment]
I use app-engine and objectify. I have my objectify code in its own git repo, and pull it in as a jar dependency in the app-engine project. This works quite well.

**Comment by sekys** [comment]
+1

**Comment by guillaumeblaquiere** [comment]
+1
