### ISSUE TITLE
Support empty fields when saving

### ISSUE THREAD

**Issue by GabiAxel** [objectify/objectify#286]
There are cases when we want to represent that a field has no value at all. Currently the closest solution is to set it to null, but that means the datastore will have that field with null value rather than no value at all for that entity. Ideally something like Java 8 Optional or Scala Option would be best to represent such case, but for Java 7 I propose adding a field annotation that would mean "on saving, if this field's value is null, don't save it to the datastore".

**Comment by stickfigure** [comment]
`@IgnoreSave(IfNull.class)`

:-)

**Comment by GabiAxel** [comment]
Great. Thanks.
