### ISSUE TITLE
@onSave does not take effect on parent properties

### ISSUE THREAD

**Issue by maelcaldas** [objectify/objectify#294]
A child class with a method annotated with @OnSave, that changes a property on parent class, the property is not persisted with that change.

Example:

class `Animal` has a property `name="a name"`

`Dog` extends `Animal` (simple hierarchy, not SubEntity)

on `Dog` I added a method

`
  @OnSave
  public void changeName() {
     super.setName("another name");
  }
`

The persisted entity was supposed to have the property `name="another name"` , but, after load, the name continue `"a name"`, that is, the change did not take effect.

I was able to workround that by doing calling changeName() immediately before save the entity, or move the `name` property to the child Entity.

**Comment by stickfigure** [comment]
There is something else going on here. Any chance you've accidentally duplicated the 'name' property in the subclass? There's nothing special about super/subclass properties or onsave methods. Post the full definition of your entity and your save/load code to the Objectify google group (or stackoverflow).
