### ISSUE TITLE
Feature suggestion: Get method to obtain the datastore Query

### ISSUE THREAD

**Issue by NicolaSpreafico** [objectify/objectify#295]
Hello,
As I can see from the [code](https://github.com/objectify/objectify/blob/master/src/main/java/com/googlecode/objectify/impl/QueryImpl.java), inside the `QueryImpl`class there is a `current`object which is the low-level datastore query.

Because I'm doing some statistics on the executed query, I need to access to the _raw _query.
I'm wondering if you can provide a get method to extract the query.

Regards

**Comment by stickfigure** [comment]
Closing due to age. If that's an issue, comment and we can reopen.
