### ISSUE TITLE
@AlsoLoad issue?

### ISSUE THREAD

**Issue by renaudcerrato** [objectify/objectify#296]
I read that using `@AlsoLoad` on a member field will raise an exception if both names exist. From my understanding that would kill the purpose of it, since when the POJO will be saved for the first time after the migration, both names will exist for sure:

```
class A {
    // migration from "bar" to "foo"
    @AlsoLoad("bar") String foo;
}
``` 

On the first load, `A.foo` will be loaded with the value previously stored in `bar`. Then, I may update `foo` and commit. On the next load, an exception will be raised since both `foo` and `bar` exist?

**Comment by renaudcerrato** [comment]
Anyone?

**Comment by stickfigure** [comment]
This is a question for the support forum (google group), not the issue tracker. But in short, if you have @AlsoLoad("bar") then you can't have a field 'bar'. If you don't have a field 'bar', you won't save it when you commit your entity.
