### ISSUE TITLE
id() and key() queries seems stoped to work on 5.1.9

### ISSUE THREAD

**Issue by Renascienza** [objectify/objectify#297]
Trying run this kind of query:

`MyEntity entity = OfyService.ofy().load().type(MyEntity.class).id(myId).now();`

I get this output: 

> java.lang.IllegalArgumentException: @Id fields cannot be filtered on. Perhaps you wish to use filterKey() instead?

Digging on QueryImpl code, I found this message and this comment:

**"We used to try to convert filtering on the id field to a __key__ query, but that tended to confuse users about the real capabilities of GAE and Objectify. So let's force users to use filterKey() instead."**

I am doing something wrong?

**Comment by stickfigure** [comment]
That query you show works fine, and is a great way to load an entity. The error message you show is from a different query - you're running `ofy().load().type(MyEntity.class).filter("id", myId).first().now()`.

Filtering by id is not something the datastore supports, and Objectify's way of "faking it" was inconsistent and confusing. If you need to perform inequality filters on keys, you can do so with the `filterKey()` method, which is just shorthand for `filter("__key__", value)`.

So: **Do** load entities by id or key. **Don't** try to filter entities by id value. If you really know what you're doing, you can filter by keys, but it's a fairly rare case.
