### ISSUE TITLE
@Parent must be in Abstract class and not Concrete implementation

### ISSUE THREAD

**Issue by branks** [objectify/objectify#299]
I have created a class as below :

```
@Entity @Cache
abstract class Entry {
  @Id Long id;
  long timeCreated;

  protected Entry () {}

  protected Entry (long timeCreated) {
    this.timeCreated = timeCreated;
  }
}
```

And then I have two concrete implementations for example

```
@Subclass(index=true) @Cache
class UserEntry extends Entry {
  @Parent Ref<User> parent;

  protected UserEntry () {}

  protected UserEntry(Ref<User> parent) {
    super(System.currentTimeMillis());
    this.parent = parent;
  }
```

```
@Subclass(index=true) @Cache
class ShopEntry extends Entry {
  @Parent Ref<Shop> parent;

  protected ShopEntry () {}

  protected ShopEntry(Ref<Shop> parent) {
    super(System.currentTimeMillis());
    this.parent = parent;
  }
```

Any time I try to create a Ref to either a UserEntry or a ShopEntry, the Ref does not contain the parent key, and therefore cannot be loaded. 

As a work around, I have had to use a generic to specify the parent type in Entry and then create an `@Parent Ref<T>`, however I feel like this is something I should be able to do?

**Comment by stickfigure** [comment]
Honestly, I think making the superclass generic so you can specify the parent type is the right answer here.
