### ISSUE TITLE
Embedded Classes dosen't get updaded

### ISSUE THREAD

**Issue by mpasio** [objectify/objectify#300]
I have a "User" entity and a nested Embedded Class "Options" like the code snippet below. However, the change of value in the Options class does NOT always get updated when I change & save it after I running this code "OfyService.ofy().save().entity(user);" 

Anyone aware of this issue ? anything change its related the  @Cache annotation? Thanks.

@Entity
@Cache
public class User {
	@Id Long id;
	Options options;
	...

	public static class Options {
		Boolean optNotification;
		...
	}
}

**Comment by stickfigure** [comment]
This sounds like a support question better suited for the Google Group or stackoverflow. It's hard to say what's going on here - I suggest posting to the Google Group. Embedded classes work fine.
