### ISSUE TITLE
Guide for upgrading from 5.0 to 5.1?

### ISSUE THREAD

**Issue by jart** [objectify/objectify#304]
@stickfigure: Is there a guide for upgrading from Objectify 5.0.x to 5.1.x? I'm noticing some significant API changes. For example https://github.com/objectify/objectify/commit/754e40a6c6786bf9b36badba2044436672addc9d which isn't documented in the [5.1 release notes](https://github.com/objectify/objectify/wiki/ReleaseNotes#51).

At this moment, here are the two big errors I'm seeing:

1. error: cannot find symbol: ObjectifyFilter.complete();
2. java.lang.IllegalStateException: You have not started an Objectify context. You are probably missing the ObjectifyFilter. If you are not running in the context of an http request, see the ObjectifyService.run() method.

I could fix these errors myself if I sat down and studied the commit history. But I thought I'd come to you for advice. Because I'm sure there's other things that need to be taken into consideration.

For example, does upgrading from 5.0.x to 5.1.13 require datastore migration, like v4 -> v5 did? Also, what would you say are the most important benefits of the 5.1 release? One thing I find appealing is a bug fix documented in the [5.1.6 release notes](https://github.com/objectify/objectify/wiki/ReleaseNotes#516).

**Comment by stickfigure** [comment]
Feel free to email me privately with more specific questions, I'm already under NDA and I'm happy to help. Going from 5.0 to 5.1, the only breaking change is what was mentioned in the release notes:

"If you are using Objectify outside of a normal GAE http request (eg, unit tests or the the remote api), there is a new method you must invoke. See javadocs for ObjectifyService.run(). The old ObjectifyFilter.complete() method has been removed."

In the past, the objectify context was created out of thin air as necessary and you could just call ObjectifyFilter.complete() to clean up any pending async futures. With 5.1 it's a little more structured, you need to start a context explicitly (via ObjectifyService.begin()) and close it. If you are using the ObjectifyFilter it just works normally. If you are using Objectify outside of the filter (say, in unit tests or via the remote API) it's just a question of either doing:

```
ObjectifyService.run(()->{
    // your work
});
```

Or using the `begin()` method in a try-with-resources, or just managing the close yourself like this:

https://github.com/objectify/objectify/blob/master/src/test/java/com/googlecode/objectify/test/util/TestBase.java

**Comment by stickfigure** [comment]
No data migrations are necessary going from 5.x forward, nor do I expect any further changes since there is now a 1-to-1 relationship between java structures and low-level api structures thanks to `EmbeddedEntity`.

**Comment by jart** [comment]
Cool. Thank you for the clarification. If I have any further questions, I'll update this issue or email you directly.
