### ISSUE TITLE
Objectify filter not working when using Endpoints with basic or manual scaling

### ISSUE THREAD

**Issue by tsanidas** [objectify/objectify#307]
I have an app based on Endpoints that uses Objectify.  When I leave it with the default/automatic scaling, everything works great.  Once I enable basic scaling, though, I get the following exception when executing the endpoint method:

```
[INFO] java.lang.IllegalStateException: You have not started an Objectify context. You are probably missing the ObjectifyFilter. If you are not running in the context of an http request, see the ObjectifyService.run() method.
[INFO]  at com.googlecode.objectify.ObjectifyService.ofy(ObjectifyService.java:44)
[INFO]  at com.myco.myapp.dao.datastore.OfyService.ofy(OfyService.java:62)
```

The good news is that this goes away when you enable RequestDispatcher support in the web.xml file like so.  I think this is a documentation issue, then, but I didn't know if everyone would agree if I edited the Wiki page directly.  Here is the proposed web.xml entry, which worked for me:

```
    <filter>
        <filter-name>ObjectifyFilter</filter-name>
        <filter-class>com.googlecode.objectify.ObjectifyFilter</filter-class>
    </filter>
    <filter-mapping>
        <filter-name>ObjectifyFilter</filter-name>
        <url-pattern>/*</url-pattern>
        <dispatcher>REQUEST</dispatcher>
        <dispatcher>INCLUDE</dispatcher>
        <dispatcher>FORWARD</dispatcher>
    </filter-mapping>
```

**Comment by NielsFC** [comment]
Thanks for that workaround!
