### ISSUE TITLE
LogAndContinueErrorHandler handleServiceError: Service error in memcache

### ISSUE THREAD

**Issue by shashi2235** [objectify/objectify#309]
MemcacheServiceException: Memcache put: Set failed to set 1 keys.
This throwing exception, while saving an entity. 
It should not throw exception, it should just log the error.

**Comment by Malleswari103095** [comment]
Hi. We've been facing the same log, which makes us think there is some error in the request handling. Should it really throw error?

**Comment by stickfigure** [comment]
Objectify doesn't throw an error on memcache error, it just logs the full stacktrace and continues. Please doublecheck what you think is happening; if you really think Objectify is throwing an exception, post the stacktrace.

Closing this for now; I'll reopen it if you have more detail.
