### ISSUE TITLE
Filter operator = and == 

### ISSUE THREAD

**Issue by andrewzhaosc** [objectify/objectify#310]
The wiki says == is supported and is default if there is no operator specified. 

The javadoc says "using the same syntax as the GAE/Python query class.", but the GAE python query syntax only allows "(=, !=, <, <=, >, >=, IN)".  Additionally the javadoc does not list == as a valid operator.

Please correct the documentation to describe the correct behavior.

**Comment by stickfigure** [comment]
The documentation is actually correct. Both `=` and `==` are supported, as is `!=` and `<>`.  The javadoc does not enumerate all the possibilities, but I've added a note about the aliasing there.
