### ISSUE TITLE
Feature request: Way to make a query execute "now"

### ISSUE THREAD

**Issue by davidsantiago** [objectify/objectify#314]
I've been searching the API docs and can't seem to find a way to do it. Once you are trying to load() a type(), all you can get from that are first(), iterable(), or list(). It appears that the only one that awaits the execution of the query is first(), which leaves you in a weird place if you want a List result, but you want it to execute now and await it. The only way I've found to make this work is the following:

``` java
List<SomeRecord> preexistingRecords = ObjectifyService.ofy().load().type(SomeRecord.class).list();
SomeRecord realizeNow = preexistingRecords.get(0); // Force an await on the result. 
```

Apologies if I've wound up off base here, but I promise, I really have been through the docs diligently.

**Comment by arsenicraghav** [comment]
Have you tried this :
`SomeRecord preexistingRecord
= ObjectifyService.ofy().load().type(SomeRecord.class).first().now();`

**Comment by stickfigure** [comment]
Anything which materializes a result will complete the asynchronous operation. As @arsenicraghav points out, calling now() on a single-element result will complete the operation. Calling any method on a `List` will complete a list-based operation; try `size()`.
