### ISSUE TITLE
Index on list of nested objects

### ISSUE THREAD

**Issue by Salmondx** [objectify/objectify#316]
Hi!
Is it possible in objectify to index list of nested properties?
I mean this:

```java
class Test {
  @Id Lond id;
  List<Embedded> embedded;
}
```
And fields inside ```Embedded``` are indexed:
```java
class Embedded {
  @Indexed private String id;
}
```
So i want to find a ```Test``` object by value in its nested embedded objects field.

**Comment by stickfigure** [comment]
Please post this question to the mailing list (the Google Group). Or stackoverflow. The issue tracker is not a good place for tech questions - sorry!
