### ISSUE TITLE
Inject a MemcacheService factory to EntityMemcache class

### ISSUE THREAD

**Issue by zhaoyan1117** [objectify/objectify#319]
Can we modify the [EntityMemcache contructor](https://github.com/objectify/objectify/blob/master/src/main/java/com/googlecode/objectify/cache/EntityMemcache.java#L166-L173
) to take in a MemcacheService factory? So users can supply a custom implementation of memcache service.

Happy to open a PR if this is welcomed.

**Comment by stickfigure** [comment]
Sure - a PR would be great :)

**Comment by zhaoyan1117** [comment]
Done! https://github.com/objectify/objectify/pull/320 @stickfigure thx

**Comment by zhaoyan1117** [comment]
resolved as [5.1.15](https://github.com/objectify/objectify/releases/tag/5.1.15) is out.
