### ISSUE TITLE
Is there a reason for 'PendingFutures' being a static class instead of being Objectify bound?

### ISSUE THREAD

**Issue by nbali** [objectify/objectify#326]
Scenario that triggered this issue:

We have a ```Objectify``` context properly initialized by ```ObjectifyFilter``` for the whole request. We are using a highly volatile entity. During that request after some execution and already having that entity in the objectify local ```Session``` cache we need the current _global_ state of that entity from the datastore/memcache. Doesn't matter if it is memcached or not, we just want to skip the local cache. Also we don't need the overhead a transaction provides.

We solved this by using
```java
		try (Closeable closeable = ObjectifyService.begin()) {
			return ofy().load().type(c).id(id).now();
		}
```

The problem we faced is that during the ```close()``` method ```PendingFutures.completeAllPendingFutures();``` is called which is a static class with a thread-local collection of pending futures. This call waits for a ```Future.get``` on all of them. It even waits for the requests started by the external ```Objectify``` context. I think it should only wait the requests launched with the "current" ```Objectify``` instance, and the futures should be collected to where they belong.

Am I missing a point here on the why?

**Comment by stickfigure** [comment]
This sounds like a very strange use case that I'd love to hear some more detail about, but let me see if I can find a better way around your problem. What I'm hearing is that you want to evict something from the session cache. It's true that there are currently no public methods to do this, but if you're this knee-deep in the code you should be able to do this:

1. Subclass `ObjectifyImpl`, add an `evict(Key<?>)` method. The method body is `getSession().keys().remove(key);`
1. Subclass `ObjectifyFactory`, override `begin()` so that it returns your `ObjectifyImpl` subclass.

Now you can evict any key from the session: `((MyOfyImpl)ofy()).evict(key);` Not super pretty and maybe there should be a public evict() method; it would help to have a really convincing use case.

In answer to your question why `completeAllPendingFutures()` work the way it does, the answer is mostly "history". The cache code predates the transaction-as-a-function programming model, and the main goal was to ensure that the cache is kept in sync by the end of a request. The design of Objectify does not anticipate programmers calling begin() more than once in a request. That may change in the future, but it's where we are now.

**Comment by nbali** [comment]
/off
The tricky part is that we don't actually want to evict it. We just want to bypass it for the current call. The reason for that is that we obviously built our application on the logic how objectify local cache works. So getFoo() on the same id returns not just the same data, but literally the same pojo every single time (I know there are exceptions, but I'm talking about the simplest use case). So we might need the same pojo with getFoo() _before_ and _after_ this "magical" bypassing get. If we evict it we lost the old and the next call will fetch a new one.

For example imagine that we modify an entity and want to save it, but for legacy/whatever reason we don't use the load-function.apply-save methodology, but we literally have a save(Foo) method. During that we might want to fire an event (audit, trigger, whatever) that might require what has changed. In order to do that we have to load the original state from memcache/datastore and compare with the new one, but we don't want to replace the local copy in the session cache.

The previous example might be solved without this, but our next case is much more complicated. We have a high concurrency system, and we have a few entities that might be accessed and modified concurrently. Also assume that the read-write ratio isn't near 1:1, but the read is _significantly_ higher. Obviously in that case we would like to utilize the cache, both local an memcache. BUT due to the mentioned usage that data might go stale rather quickly. In that case we need the newest state. For such amount of calls transactions are expensive. Both time and datastore-wise. So we need the shared state, but we don't care if it's from memcache - so we don't need the most consistent data from datastore like a transaction would return -, and more importantly we don't need the transaction overhead. Basically what we need is similar to what "TransactorNo.transactOnce" does, but without beginning/comitting/rollbacking any transaction at all. :) (As for real life examples: job/task cancellation/postponing, concurrency limitation, rate limit management, etc)

/on
Back to the original topic :) Unless I'm mistaken anything left in ```PendingFutures``` means they were executed without calling now() on the returning Result. In our application that most likely means two things:
- it was a prefetched that wasn't required yet (getAsync)
- it was stored asynchronously as a not a business-critical data (storeAsync)

So at the end we only did a "getSync" inside our newly created context - and most likely on a completely unrelated entity - yet the completeAllPendingFutures() called by close() failed with the notorious "Too much contention on these datastore entities" exception. Okay, to be precise it didn't fail as it has a try-catch around it, but creates false positive SEVERE logs. That is the reason it baffled us like "Contention issue on a get of that entity? Wat?!"

So it doesn't stop the execution, hence it's not a bug, but a rather annoying occurrence as it spams the "Error Reporting" page with false positives. (Also it has a negative effect on performance as it blocks until every call is done).

Based on my knowledge of the objectify codebase I thought it's easier to make PendingFutures ObjectifyImpl context bound than implementing an option to bypass the local cache. I couldn't find any reason if that would be an issue, but it's better to be safe than sorry.

**Comment by stickfigure** [comment]
Gotcha. There has been some progress in discussions around a rewrite of Objectify for the new Cloud SDK interface (rather than the old ApiProxy). If/when that materializes, this should be easy to resolve. Leaving it open as an enhancement request for now.

**Comment by nbali** [comment]
@stickfigure so am I right that as a quick workaround I should probably create my own ```ObjectifyService.begin()```-like method? pretty much the same without the ```completeAllPendingFutures``` call?

**Comment by stickfigure** [comment]
Sure - you can certainly do that. I'm pretty sure that will give you what you want.
