### ISSUE TITLE
Objectify unnecessarily converts String to Text at 500 characters

### ISSUE THREAD

**Issue by rickgittest** [objectify/objectify#327]
Objectify's StringTranslatorFactory converts String entity properties to Text if they are longer than 500 characters. This is inconsistent with the current version of datastore, which allows indexed strings up to 1500 bytes in length. This not only restricts indexing strings longer than 500 characters, but also restricts projection properties to 500 characters, as well, a significant restriction in my application.

The code in StringTranslatorFactory to fix is highlighted below:

```
			protected Object saveValue(String value, boolean index, SaveContext ctx, Path path) throws SkipException {
				// Check to see if it's too long and needs to be Text instead
				**if (value.length() > 500) {**
					if (index)
						log.log(Level.WARNING, "Attempt to index a String which has been automatically converted to Text. The property is at " + path);

					return new Text(value);
				} else {
					return value;
				}
			}
```
I respectfully request that this simple fix be prioritized and included in release 5.1.18. Thank you.

**Comment by stickfigure** [comment]
Oh hey, that's news. Fixed, it'll go out in the next release (very soon).

**Comment by rickgittest** [comment]
Fast! Wow!

**Comment by stickfigure** [comment]
This should be in maven central as v5.1.18. Cheers!
