### ISSUE TITLE
Unnecessary memcache.get inside EntityMemcache.putAll for kinds without @Cache

### ISSUE THREAD

**Issue by nbali** [objectify/objectify#329]
Reproduction:
- initialize ofy() in a way that caching is enabled globally (requires an ```@Entity``` class to be registered with ```@Cache``` annotation -> see ```Registrar.register(Class<T>)```) so it uses ```CachingAsyncDatastoreService```
- register a kind that doesn't have ```@Cached```
- call ```ofy().load().type(TypeWithoutCached.class).id("dummyId").now()```
- it will result in a ```/datastore_v3.Get ``` and ```/memcache.Get```

Severity:
- only affects performance

Description:
Inside ```EntityMemcache.putAll(Collection<Bucket> updates)``` (called from ```CachingAsyncDatastoreService.get(Transaction txn, Iterable<Key> keys)``` by ```memcache.putAll(uncached);```) with the ```updates``` list ```cachePutIfUntouched``` is called.

```cachePutIfUntouched``` filter entities without ```@Cache``` properly, and it only inserts what it should, but this way the result contains only ```Key```s that were actually updated. Due to the filtering this result list doesn't contain non-```@Cached``` entities' keys.

After it return it's size is compared with the original input's size. It won't match. (```if (good.size() == updates.size())```)

The logic will add the non-```@Cached``` entities' keys into the ```bad``` list. We will call ```cacheGetAll``` with that.

... and THIS is the problem. We do an unnecessary memcache.get inside that method.

Calling ```empty``` later works just fine, as we do the same kind of filtering inside like we did in ```cachePutIfUntouched```.

**Comment by nbali** [comment]
@stickfigure it's not a complicated fix, I just don't really have the time right now, feel free to fix it if you want to, or just wait for me having capacity for a contribution

@ttozser @gabor-farkas fyi

**Comment by stickfigure** [comment]
Interesting - I'll take a closer look and fix it this afternoon. Thanks!

**Comment by stickfigure** [comment]
I looked closer. `EntityMemcache.cachePutIfUntouched()` excludes uncacheable items and `KeyMemcacheService.putIfUntouched()` will perform no-op if the input map is empty.

I also added a test to verify this behavior (`CachingUncacheableTests`). It executes the behavior you describe; the test passes. If there's something else I can do here (or you can figure out how to get that test to fail) we can re-open this issue.

**Comment by nbali** [comment]
I checked your commit and you missed the part I required a class to be registered with @Cache to enable caching globally.

**Comment by stickfigure** [comment]
Ah! Will try that.

**Comment by stickfigure** [comment]
Done, release 5.1.19 on way to maven central now. 

Thanks for hunting that down!
