### ISSUE TITLE
Appengine Flex compatibility

### ISSUE THREAD

**Issue by rahultongia** [objectify/objectify#333]
Hi Jeff,

Do you plan to build Objectify on the Rest API anytime soon? I am using old managed vm environment and can still run on the "compatibilty" mode so objectify works for now, but need to decide on an eventual migration path.

Regards,
Rahul

**Comment by stickfigure** [comment]
Yes - this is about to kick off: https://github.com/objectify/objectify/wiki/DesignOfObjectify6

Watch the project for progress.

**Comment by rahultongia** [comment]
Thanks Jeff.

**Comment by sgammon** [comment]
Is there a way the community can help with Objectify 6? I'd love to jump in and contribute.

**Comment by rahultongia** [comment]
@stickfigure by any chance do you have some timeline for release of Release of version 6? Also, as @sgammon mentioned, is there any way community could support you with that. Happy to contribute.

**Comment by stickfigure** [comment]
"Real Soon Now"? Hard to predict a specific date but I'm actively working on it. You can follow progress on the v6 branch.

The best contribution would be some way to get a baby to sleep through the night :)

**Comment by rahultongia** [comment]
@stickfigure so far the testing of alpha release on my test suite is looking good. I am testing on stage for flex and standard, both on java8. Timeline for further releases? Let me know if I should write some tests for Objectify's test suite which helps in major release.

**Comment by stickfigure** [comment]
Good to hear! At this point I'm just waiting for some feedback from G before cutting a beta. There haven't been any significant code changes since the alpha.

If there is any test coverage you feel is missing, yes please submit PRs!

**Comment by sgammon** [comment]
@stickfigure we've moved to new software due to the delays here. Apologies and good luck

**Comment by stickfigure** [comment]
Objectify 6.0 beta 1 is now out.

**Comment by stickfigure** [comment]
v6 is formally released
