### ISSUE TITLE
Delete all entities in Kind or Delete a Kind

### ISSUE THREAD

**Issue by prasannaboppe** [objectify/objectify#335]
How to delete all entities in a Kind in single shot (programmatically). By getting entities list and deleting is not ideal for large number of entities. any better solution for this? Thanks

**Comment by Oziomajnr** [comment]
You can list the keys instead of the entities and batch delete them using the keys, if the entities are very many, you can use some form of job/map reduce.

**Comment by stickfigure** [comment]
This is not a feature that is baked in to the datastore. GAE has a "datastore admin" tool that uses map/reduce to delete all entities via a UI. Or you can use map/reduce yourself to delete all entities. But this is definitely a higher-level operation than Objectify can help with.
