### ISSUE TITLE
Building Composite Index

### ISSUE THREAD

**Issue by prasannaboppe** [objectify/objectify#336]
I have list of Entities indexed by 3 keys like date, language and type. When I'm trying execute a GQL Query "select * from DAILYCHALLENGES where date >= someday and date <= someday and language = 2 and type = 2", it's giving an error like there is no user provided index. I build my composite index like below
`indexes:
- kind: DAILYCHALLENGES
  properties:
  - name: date
  - name: language
  - name: type`

Can you help me in this? I want to execute above type of query. Thanks

**Comment by stickfigure** [comment]
Please post this question to stackoverflow or the objectify google group; the issue tracker is not a good place for support requests. Thanks!
