### ISSUE TITLE
Support new Java 8 date/time classes

### ISSUE THREAD

**Issue by PeterKnego** [objectify/objectify#337]
As Java8 runtime is now supported as standard environment, it would be sensical to support new Java8 time/date classes:  OffsetDateTime, ZonedDateTime, etc..

Problem: New Java8 date/time classes contain both timestamp info (Instant) and offset or timezone info (OffsetDateTime, ZonedDateTime). OTOH, Datastore natively supports only timestamp fields which do not contain offset and/or timezone info.

Qs: How to support new Java8 time/date classes? 
Could this be done via custom serializer or extension?

**Comment by stickfigure** [comment]
Objectify6 will be JDK8+ so it will at least support Instant out of the box.

I'm not sure what to do about the more exotic time classes. One option is to convert to/from the ISO-8601 string representation, but that won't sort. Another is to use a custom string format that satisfies the `compareTo` of the Java classes, but that wouldn't necessarily be human-friendly.

This requires some discussion; I'm open to ideas. It's easy to add arbitrary translators; perhaps any experimental translators should require being registered explicitly (like the joda translators) until we decide on a permanent format.

**Comment by PeterKnego** [comment]
Since timestamp + offset/zone do not map to any of Datastore native fields, we'd have to use two fields that are logically linked. This would probably rule out using translators which only do single property <> single field translation?

Maybe we could use embedded objects?

**Comment by stickfigure** [comment]
There's really no value in using multiple fields; it makes indexing and querying difficult and expensive (lots more indexes required, including datastore-indexes.xml). The best approach will be some sort of String translation. We can generate something that matches comparator behavior; OffsetDateTime would be something like: "2017-09-28T10:50:12.3456Z2017-09-28T18:50:12.3456" (Z is an implicit separator; the second part is the localdatetime so it sorts correctly; the offset is easy to calculate).

https://docs.oracle.com/javase/8/docs/api/java/time/OffsetDateTime.html#compareTo-java.time.OffsetDateTime-

ZonedDateTime is also Comparable but the behavior does not appear to be documented. I'd have to look at the JDK source but my guess is it is similar to OffsetDateTime, although the same format won't work for us (we'll need to add an explicit TZ to reconstitute the original form).

**Comment by PeterKnego** [comment]
Imho, the point of having datetimes with offset is to answer queries like: find all datetimes where local time is 5pm (for instance this is useful for sending notifications at certain local time). Would the proposed format enable such queries?

ZonedDateTime is altogether more complicated because time offset of geographical zones is not fixed, i.e. it changes based on different (local) daylight saving definitions. JVM library keeps an updated list of zones/offsets/dst definitions to be able to translate geo zone -> time offset.

**Comment by stickfigure** [comment]
> find all datetimes where local time is 5pm

Assuming you have an OffsetDateTime field, how would you even issue this query? Objectify would have to include some sort of query language/builder that understands the time objects. Plus, what do you do about the people that want different kinds of ordering (ie, the Comparator<?> ordering)? This could end up needing a half-dozen indexed properties just to support one field, plus now users will need various combinations of them in datastore-indexes.xml.

This is the kind of thing that users can manage pretty well on their own (ie, inside your `MyEntity.setMyOffsetDateTimeField()` you can break down the value into component parts and save them as indexed private fields). There's a lot of different approaches; to me this doesn't feel like the kind of behavior that should be built into Objectify.

**Comment by PeterKnego** [comment]
Hmm, agreed.

**Comment by PeterKnego** [comment]
There seems to be very little value-add in supporting Java 8 date-time classes (OffsetDateTime, ZonedDateTime) beyond the basic Instant class.
