### ISSUE TITLE
Suggestion: use logging level WARNING instead of SEVERE to log memcache failures that don't cause out-of-sync memcache

### ISSUE THREAD

**Issue by HansBrende** [objectify/objectify#340]
Failed memcache lookups aren't a huge deal, since they simply fall back to datastore lookups. Using logging level `SEVERE` for temporary memcache outages has the unwanted side-effect of Stackdriver notifications sending me **lots of unnecessary e-mails** about an outage that (1) I can't do anything about, and (2) that doesn't result in an out-of-sync memcache, or interfere in any way with the execution of my program.

This could be fixed by simply changing the line: 

`		this.memcache.setErrorHandler(ErrorHandlers.getConsistentLogAndContinue(Level.SEVERE));
`

to 

`		this.memcache.setErrorHandler(ErrorHandlers.getConsistentLogAndContinue(Level.WARNING));
`

in the [`EntityMemcache`](https://github.com/objectify/objectify/blob/master/src/main/java/com/googlecode/objectify/cache/EntityMemcache.java) constructor.

Here's an example of an exception that is occasionally caught and ignored when I call `CachingDatastoreService.get(Iterable<Key> keys)`, but gets e-mailed to me anyway by Stackdriver notifications:

> com.google.appengine.api.memcache.MemcacheServiceException: Memcache getIdentifiables: exception getting multiple keys
> 	at com.google.appengine.api.memcache.MemcacheServiceApiHelper$RpcResponseHandler.handleApiProxyException(MemcacheServiceApiHelper.java:77)
> 	at com.google.appengine.api.memcache.MemcacheServiceApiHelper$1.absorbParentException(MemcacheServiceApiHelper.java:122)
> 	at com.google.appengine.api.utils.FutureWrapper.handleParentException(FutureWrapper.java:56)
> 	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:95)
> 	at com.google.appengine.api.memcache.MemcacheServiceImpl.quietGet(MemcacheServiceImpl.java:28)
> 	at com.google.appengine.api.memcache.MemcacheServiceImpl.getIdentifiables(MemcacheServiceImpl.java:61)
> 	at com.googlecode.objectify.cache.KeyMemcacheService.getIdentifiables(KeyMemcacheService.java:75)
> 	at com.googlecode.objectify.cache.EntityMemcache.getAll(EntityMemcache.java:225)
> 	at com.googlecode.objectify.cache.CachingAsyncDatastoreService.get(CachingAsyncDatastoreService.java:252)
> 	at com.googlecode.objectify.cache.CachingAsyncDatastoreService.get(CachingAsyncDatastoreService.java:215)
> 	at com.googlecode.objectify.cache.CachingDatastoreService.get(CachingDatastoreService.java:137)
...

> Caused by: com.google.apphosting.api.ApiProxy$CapabilityDisabledException: The API call memcache.Get() is temporarily unavailable: Memcache is temporarily unavailable.
> 	at com.google.apphosting.utils.runtime.ApiProxyUtils.getRpcError(ApiProxyUtils.java:136)
> 	at com.google.apphosting.runtime.ApiProxyImpl$AsyncApiFuture.setRpcError(ApiProxyImpl.java:601)
> 	at com.google.apphosting.runtime.ApiProxyImpl$AsyncApiFuture.failure(ApiProxyImpl.java:589)
> 	at com.google.apphosting.runtime.http.HttpApiHostClient.receivedResponse(HttpApiHostClient.java:224)
> 	at com.google.apphosting.runtime.http.JettyHttpApiHostClient$Listener.onComplete(JettyHttpApiHostClient.java:146)

So is a failed memcache lookup which falls back to a successful datastore lookup really "severe" enough to be worthy of an e-mail?

Javadocs say:
> In general SEVERE messages should describe events that are of considerable importance and which will prevent normal program execution.  

... which doesn't seem to be the case for memcache lookup errors, since the final result (falling back to datastore lookup) is still 100% correct, so the program can still function normally. I would suggest changing the default logging level for memcache lookup errors to `WARNING`, which would have the happy side-effect of preventing the unnecessary e-mails.

**Comment by HansBrende** [comment]
On closer inspection, it looks like the CachingDatastoreService *is* falling back to a DatastoreService lookup, but logging the error anyway with Level.SEVERE, which sends me an e-mail through Stackdriver Notifications. 

So new question: shouldn't the error be logged with a Level.WARNING, since memcache service errors are apparently not infrequent? Or shouldn't there be a method somewhere in CachingDatastoreService allowing me to change the logging level? I really don't want to get an e-mail every time the MemcacheService is temporarily unavailable.

**Comment by stickfigure** [comment]
This seems to no longer be relevant with v6
