### ISSUE TITLE
How can apply Projection Queries with Key in Objectify

### ISSUE THREAD

**Issue by AxeemHaider** [objectify/objectify#342]
I read this is possible to project the queries in datastore using Objectify. But didn't found any documentation or any article on this Even not in official documentation. From where I can read about this ?

My question is how can I apply project on entity when I'm getting it with Key

**ProjectionEntity**

```
@Entity
public class ProjectionEntity {

@Id long id;

String cont1, cont2, cont3; 
}
```
GetEntity What I'm trying.

```
Key key = Key.create(ProjectionEntity.class, 123);
ProjectionEntity pe = (ProjectionEntity) ofy().load().key(key).project("cont1","cont2").now();  // I know this is not valid 

 pe.getCont1();
 pe.getCont2();
```
How can I do something like this ?

**Comment by stickfigure** [comment]
You can't; this isn't supported by the underlying datastore. These questions are really best for stackoverflow or the google group; this is an issue tracker.
