### ISSUE TITLE
Support nested embedded Maps

### ISSUE THREAD

**Issue by JeffBolle** [objectify/objectify#347]
```
  public class GCDTests {

      @Entity
      class TestObj{
          @Id Long id;
          Map<String, Object> data = getNestedMap();
          public TestObj(){}
      }

      public static Map<String, Object> getNestedMap(){
          HashMap<String, Object> map = new HashMap<>();
          HashMap<String, Object> map2 = new HashMap<>();
          HashMap<String, Object> map3 = new HashMap<>();
          map.put("level", 1);
          map2.put("level", 2);
          map3.put("level", 3);
          map3.put("val", "alldone");
          map2.put("embed", map3);
          map.put("embed", map2);
          return map;

      }

      public void testNestedMap(){
          ObjectifyService.register(TestObj.class);
          TestObj testObj = new TestObj();
          Key k = GCDHelper.saveObject(testObj);
      }

      public static void main(String[] args){
          GCDTests tester = new GCDTests();
          tester.testNestedMap();

      }
  }
```
saveObject() is a utility for running outside of AppEngine.
```
    public static com.googlecode.objectify.Key saveObject(Object obj){
        com.googlecode.objectify.Key ret = ObjectifyService.run(new Work<com.googlecode.objectify.Key>() {
            @Override
            public com.googlecode.objectify.Key run() {
                return ofy().save().entity(obj).now();

            }
        });
        return ret;
    }
```

Running this yields:
```Exception in thread "main" com.googlecode.objectify.SaveException: Error saving  com.corp.package.GCDTests$TestObj@5d9b7a8a: java.lang.IllegalStateException: Embedded Map keys must be of type String/Enum/Key<?> or field must specify @Stringify
	at com.googlecode.objectify.impl.EntityMetadata.save(EntityMetadata.java:117)
	at com.googlecode.objectify.impl.WriteEngine.save(WriteEngine.java:69)
	at com.googlecode.objectify.impl.SaverImpl.entities(SaverImpl.java:60)
	at com.googlecode.objectify.impl.SaverImpl.entity(SaverImpl.java:35)
	at com.corp.package.gcp.GCDHelper$2.run(GCDHelper.java:158)
	at com.corp.package.gcp.GCDHelper$2.run(GCDHelper.java:155)
	at com.googlecode.objectify.ObjectifyService.run(ObjectifyService.java:61)
	at com.corp.package.GCDHelper.saveObject(GCDHelper.java:155)
	at com.corp.package.GCDTests.testNestedMap(GCDTests.java:53)
	at com.corp.package.GCDTests.main(GCDTests.java:58)
Caused by: java.lang.IllegalStateException: Embedded Map keys must be of type String/Enum/Key<?> or field must specify @Stringify
	at com.googlecode.objectify.impl.translate.EmbeddedMapTranslatorFactory.create(EmbeddedMapTranslatorFactory.java:57)
	at com.googlecode.objectify.impl.translate.Translators.create(Translators.java:143)
	at com.googlecode.objectify.impl.translate.Translators.get(Translators.java:122)
	at com.googlecode.objectify.impl.translate.ObjectTranslatorFactory$1.saveSafe(ObjectTranslatorFactory.java:37)
	at com.googlecode.objectify.impl.translate.NullSafeTranslator.save(NullSafeTranslator.java:31)
	at com.googlecode.objectify.impl.translate.EmbeddedMapTranslatorFactory$1.save(EmbeddedMapTranslatorFactory.java:111)
	at com.googlecode.objectify.impl.translate.EmbeddedMapTranslatorFactory$1.save(EmbeddedMapTranslatorFactory.java:69)
	at com.googlecode.objectify.impl.PropertyPopulator.save(PropertyPopulator.java:130)
	at com.googlecode.objectify.impl.translate.ClassPopulator.save(ClassPopulator.java:156)
	at com.googlecode.objectify.impl.translate.ClassTranslator.saveSafe(ClassTranslator.java:131)
	at com.googlecode.objectify.impl.translate.NullSafeTranslator.save(NullSafeTranslator.java:31)
	at com.googlecode.objectify.impl.EntityMetadata.save(EntityMetadata.java:113)
	... 9 more
```

I'm using Objectify 6.0a1.
I'm not sure the best way to approach this. My actual use case is more complex than my test case and I need to be able to Objectify arbitrary Map<String, Object> objects.  I can't annotate the nested maps, and Stringify only works at the top level. How should I go about handling these maps?

**Comment by stickfigure** [comment]
I'm pretty sure Objectify has never supported this kind of behavior. I added this test to the v5 branch and it fails in a similar way.

Objectify was never intended to do this kind of dynamic structure introspection; it works off a static metamodel constructed at registration time. There are some special cases like this where dynamic introspection is used, but it's not especially thorough since Java erases generic type info.

That said, I can get this working. It can't be very smart about values - for example, you'll always get a `HashMap` even if you save a `LinkedHashMap` or `TreeMap`. I'm a little concerned when you say "My actual use case is more complex" - what other edge cases are involved?

**Comment by stickfigure** [comment]
Also: The only type of key that will be allowed in a nested `Map` is `String`. You can't nest a map that has a `Long`, `Key<?>`, or other nonstring key; that type information gets destroyed when it gets stored as a `String` key in an embedded `Entity`.

**Comment by stickfigure** [comment]
Apparently I lied. There is not a simple fix for this.

When you store `Map<String, Object>`, Objectify can happily introspect the runtime type of a nested inner `Map` and convert it to a low-level `Entity` for storage. However, on loading, Objectify has no way of knowing that you want the `Entity` to be turned back into a `Map`. So you will not roundtrip correctly.

We would need some sort of extra flag when registering the container entity POJO to inform Objectify that when loading `Object`, all `Entity` objects should be turned into hashmaps. This is getting pretty esoteric.

**Comment by JeffBolle** [comment]
Thank you for digging in and taking a look, I really appreciate it. I didn't mean to imply that it had worked previously; this is my first exploration into Objectify.  Going down the full route you suggested is definitely making this a pretty arbitrary and esoteric use case for most people who are currently using Objectify.

At a high level the problem I'm trying to solve is that we have a robust system for serializing all of our enterprise objects POJO <--> JSON using Gson.  I was looking for a clean way to introduce Datastore into this architecture without having to write a lot of additional serialization code (since we have already done that) or re-annotate the objects from across a dozen projects.  The shortcut I was exploring was using our existing JSON serialization to turn an object into a Map<String, Obj>.  This works well and is something we use in a few other cases. 

Of course the irony here is that I've already written the code to go from an Entity back to our POJO through the Map<String, Object> --> POJO flow.  It appears to work well for some simple test objects.  

Clearly there are some shortcomings with my flow since JSON is less expressive than Datastore in terms of object types, however most of our queries are on relatively simple types (except for Dates, which was going to be my next hurdle).

**Comment by stickfigure** [comment]
Why not just keep the JSON? You could write an Objectify `Translator` that uses your Gson-based system to translate your POJO field into a string stored in the native datastore entity. The `Translator` should be pretty straightforward, but I'm happy to help. Look at `SerializeTranslatorFactory` as a guide.

**Comment by JeffBolle** [comment]
Interesting suggestion.  I believe storing the POJO as a JSON string would cause Cloud Datastore to view it as an unindexed field (depending on length). We would like to be able to take advantage of doing queries against the fields in the objects. If we wrote a Translator / TranslatorFactory for our object hierarchy, would we still need to annotate all of those objects with Objectify annotations?

**Comment by stickfigure** [comment]
Correct, storing the JSON as a string would be unindexed. However, you can add synthetic indexes via private fields that you populate with an `@OnSave` method.

If you are JSON serializing data, your Translator code is doing the work. Objectify just sees it as an Object on one side (in POJO form) and a String on the other (in low-level Entity form). So Objectify's annotations aren't involved (below the top-level POJO, that is).

If you already have code that converts between objects and String (your gson-based serializer), you can just build a Translator around this. It probably isn't more than a dozen lines of code.
