### ISSUE TITLE
How to create consistent query?

### ISSUE THREAD

**Issue by muzuro** [objectify/objectify#353]
Please consider this issue as question, it related to [this stackoverflow question](https://stackoverflow.com/q/48609649/3523298). In datastore i can create query with [strong consistency](https://cloud.google.com/datastore/docs/concepts/structuring_for_strong_consistency). I can achive this using [ancestor query](https://cloud.google.com/datastore/docs/concepts/queries#ancestor_queries). 
So i use following code with raw datastore:
```
KeyFactory userKeyFactory = datastore.newKeyFactory()
    .addAncestors(PathElement.of("UserList", "default"))
    .setKind(USER_KIND);

//...save entity

Query<Entity> query = Query.newEntityQueryBuilder()
    .setKind(USER_KIND)
    .setFilter(PropertyFilter.hasAncestor(datastore.newKeyFactory().setKind("UserList").newKey("default")))
    .build();
QueryResults<Entity> queryResults = datastore.run(query);
List<User> result = new ArrayList<>();
queryResults.forEachRemaining(entity -> result.add(transformUser(entity)));
return result; 
```

Objectiry can't work with `PathElement` so following code fails with "No class 'com.google.cloud.datastore.PathElement' was registered"
```
ofy().load().type(User.class).ancestor(PathElement.of("UserList", "default")).list()
```
I tried to use this code:
```
ofy().load().type(User.class).ancestor(datastore.newKeyFactory().setKind("UserList").newKey("default")).list()
```
Now it fails that User don't have field with `@Parent` annotation. But i haven't such entity "UserList", i need this ancestor just for query strong consistency.

**Comment by stickfigure** [comment]
Let's continue this on the stackoverflow question. I posted a comment; you seem to be on the right track.
