### ISSUE TITLE
Unnecessary guava dependency?

### ISSUE THREAD

**Issue by anbuck** [objectify/objectify#356]
In the pom.xml there is a dependency on guava, but I don't see where in the code guava is used. If I remove the guava dependency from the pom, objectify builds and tests successfully. Is the guava dependency no longer needed?

**Comment by stickfigure** [comment]
Huh. Looks like all the guava dependencies were removed in v6.

I'll remove the direct dependency from the pom, but this won't eliminate guava from your build - the google cloud SDK pulls it in. Thanks though, always good to clean up the pom!
