### ISSUE TITLE
Search using substring in entity

### ISSUE THREAD

**Issue by bhuvaneshwariarkala** [objectify/objectify#357]
Hello team,

I am developing app engine project..In that i have to seacrh using substring in few properties of the entity.

For example, if i have entity property with "testalg", i should get results by searching with string like "test"...How Can i Get this.

Please could you tell me this

Thank you in advance

**Comment by stickfigure** [comment]
This is in the FAQ:

https://github.com/objectify/objectify/wiki/FrequentlyAskedQuestions#how-do-i-do-a-like-query-like-foo

Cheers

**Comment by bhuvaneshwariarkala** [comment]
Hi,

I tried the solution suggested in the FAQ.

Like : 
List<T> sampeResult = ofy().load().type(entity).filter("serialNo >=", value.getValue())
						.filter("serialNo <", value.getValue() )
						.list();

But it is not receiving the results

**Comment by stickfigure** [comment]
Look carefully at the FAQ code - you need to add the extra unicode character to the filter value. You're doing a literal char-by-char comparison of the string value.

Conceptually, to get "foo%" you want the values between "foo" and "fooz" but instead of 'z' you use the maximal unicode character.

**Comment by bhuvaneshwariarkala** [comment]
Thank you for the quick response :)
Its working..But i have multiple properties of entity to be searched, so i am passing hashmap, and iterating throught it by passing each key value pair to the filter.but that is not working..
When I have statci string, it is working.
List<T> sampeResult = ofy().load().type(entity).filter("id1 >=", value.getValue())
						.filter("id1 <", value.getValue() + "\uFFFD" )
						.list();

But when i have key/value pair it is failing to get the values.
				List<T> sampeResult = ofy().load().type(entity).filter(value.getKey().toString() + ">=", value.getValue())
						.filter(value.getKey().toString() + "<", value.getValue() + "\uFFFD" )
						.list();

Please let me know if i miss anything .

Thanks,
Bhuvana

**Comment by stickfigure** [comment]
Put a space before the operators. `value.getKey() + " >="` (notice space before the `>=`).

**Comment by bhuvaneshwariarkala** [comment]
Hello,

\uFFFD need to be added to search for the "foo%", but what we need to add "%foo" ?

**Comment by stickfigure** [comment]
You have to store an indexed field that contains the string backwards, then filter by the inverted string.

**Comment by bhuvaneshwariarkala** [comment]
That means,

For case insensitive search one string which is lower case, and to search from beginning one more dummy indexed field with reverse string..I have to seacrh on 8 properties , so i should maintian more 16 dummy indexed fields.

**Comment by stickfigure** [comment]
Yeah, the datastore has limitations. It's not designed for fulltext search.

You're probably used to doing LIKE queries in RDBMSes, which work great as long as the data volume is small. Non-prefix LIKE queries are almost always implemented as table scans. 

Databases aren't magic; doing complex fulltext search at scale is pretty hard. If you can live with table scans, use an RDBMS. If you need something more sophisticated, consider the Search API (storing as many word fragments as you need to match). If you need something really sophisticated, consider running your own ElasticSearch cluster.

All that said, if you just want something simple using only the datastore, store an indexed list property with as many forms of the string you want to search for as necessary. Forwards, backwards, uppercase, etc.

**Comment by bhuvaneshwariarkala** [comment]
Hi,

Thanks for the quick response.

As you I told i had Indexed reverse string list , and it contains,
[3ved, 2mlbz322yz, 980898989, 3ved, zyx, cba, _dekcolnu_1ycilop/seicilop/lsc0fb10cl/sesirpretne, sulp )5( g otom]

Actual string is [Dev3, ZY223ZBLM2, 989898089, dev3, xya, abc, etc).

And was searching using the 
.filter("revereSeacrhList" + " >=", value.getValue() )
				.filter("revereSeacrhList" + " <",  value.getValue() + "\uFFFD" )

Not getting results.
Can you please tell me if iam doing something wrong here?

Thanks in advance
Bhuvana

**Comment by stickfigure** [comment]
You need to reverse the string you are searching for too. You're doing a literal match.
