### ISSUE TITLE
Case insensitive search

### ISSUE THREAD

**Issue by bhuvaneshwariarkala** [objectify/objectify#358]
Hello Team,

Do we have insensitive search in objectify?
I mean if i have "test", I should get results by searching "TEST", "Test", "tESt", etc

**Comment by stickfigure** [comment]
This is not inherently supported by the underlying datastore. However, you can manage it yourself simply by adding an extra indexed field to your POJO that saves a case-normalized version of the string. You can populate it in your setter method or in an `@OnSave` method.
