### ISSUE TITLE
Using Objectify 6 outside of App Engine

### ISSUE THREAD

**Issue by sceee** [objectify/objectify#362]
I am trying to use Objectify 6 outside of App Engine and outside an http application but I am confused how to get it running.

I tried to do the following:
```
DataStore dataStore = DatastoreOptions.newBuilder().setProjectId("myprojectid").build().getService(); // To work around https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2822
ObjectifyFactory factory = new ObjectifyFactory(dataStore);
        ObjectifyService.init(factory);
        ObjectifyService.register(Job.class);
```

But then I am receiving the following error:
`java.lang.IllegalStateException: You have not started an Objectify context. You are probably missing the ObjectifyFilter. If you are not running in the context of an http request, see the ObjectifyService.run() method.`

Is it possible to use Objectify outside of GAE/app engine and how?

**Comment by stickfigure** [comment]
I presume you are seeing that exception when you try to use Objectify. Are you calling this from a webapp, in which case you have the `ObjectifyFilter` installed? Or from some other context, in which case are you wrapping your Objectify use in `ObjectifyService.run()`?

**Comment by sceee** [comment]
@stickfigure thanks for the fastest answer on github so far for me :)
Yes, I see that error when I try to use objectify.
I am calling this in a library which I want to use to encapsulate my data access. So this is not from a webapp and I do not have the `ObjectifyFilter` installed. I am not sure how to wrap my use around `ObjectifyService.run()`, how would the `run` method look like?

In the end I am trying to achieve a library that has some methods like `getCar()` which then encapsulates `ofy().load().type(Car.class).id(carID).now();` and returns the car.

**Comment by sceee** [comment]
@stickfigure oh wait, is this the way to go?

```
Car result = ObjectifyService.run(new Work<Car>() {
            @Override
            public Car run() {
                Car result = ofy().load().type(Car.class).filter("carid", carID).first().now();
                return result;
            }
        });
```

**Comment by stickfigure** [comment]
Yep. It's somewhat prettier with a Java8 closure.

That closure will define the scope of a single Objectify session, so be careful about keeping it around for too long. In normal webapps, that session lives for a single request (the ObjectifyFilter basically just calls this method).

**Comment by sceee** [comment]
Alright, thanks for the help @stickfigure 
Now I know how to proceed :)
