### ISSUE TITLE
Query on lenth of the item in Entity

### ISSUE THREAD

**Issue by bhuvaneshwariarkala** [objectify/objectify#364]
Hello Team,

Do we have any API/work around to query based on length of the items in Entity.
For example if there are 14 and 15 length strings in entity, and want to retrieve only 14 length strings.

Thanks,
Bhuvana

**Comment by stickfigure** [comment]
You should create a synthetic index - a private, indexed field in your POJO that gets populated with the number in an `@OnSave` method.
