### ISSUE TITLE
Is Google App Engine Mandatory for Objectify

### ISSUE THREAD

**Issue by saisurya-k** [objectify/objectify#366]
I've used the following config to initialize Objectify
```java
Datastore dataStore= DatastoreOptions.newBuilder().setProjectId("id").build().getService();
        ObjectifyFactory config = new ObjectifyFactory(dataStore);
        init(config);
        register(Entity.class);
```
When I started the spring boot app I ended with the following error.
```java
2018-04-02 00:54:55.592  WARN 29508 --- [           main] c.g.a.oauth2.ComputeEngineCredentials    : Failed to detect whether we are running on Google Compute Engine.
java.net.SocketException: Network is unreachable: connect
```
I'm trying to use Objectify as ORM layer for my Google DataStore account in a spring boot application.
Dependencies used:
```xml
<dependency>
            <groupId>com.googlecode.objectify</groupId>
            <artifactId>objectify</artifactId>
            <version>6.0b1</version>
        </dependency>
        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-datastore</artifactId>
            <version>1.24.0</version>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>24.1-jre</version>
        </dependency>
```

**Comment by stickfigure** [comment]
No, Objectify v6 does not have to be run within GAE. That said, I'm not really super familiar with the process of connecting to a datastore from various environments. Try using that `Datastore` object in some manner; if it works, then it'll work with Objectify.

If the `Datastore` doesn't work, I would scrounge around the Google-supplied help resources to figure out why.

**Comment by saisurya-k** [comment]
@stickfigure Thanks for the reply. I've figured it out the issue,instead of configuring the `DataStore` this way
```java
Datastore dataStore= DatastoreOptions.newBuilder().setProjectId("id").build().getService();
```
I've tried the config as per Google Cloud Datastore Docs
```java
 Datastore datastore = DatastoreOptions.getDefaultInstance().getService();
```
along with Environment Variable 
```sh
set GOOGLE_APPLICATION_CREDENTIALS="C:\Users\username\Downloads\[FILE_NAME].json"
```
and the issue is resolved
