### ISSUE TITLE
Question about the memory cache

### ISSUE THREAD

**Issue by tim-lebedkov** [objectify/objectify#367]
memcache.Get is quite slow and seems to fetch entities one by one (Objectify 4). Would an update to version 5 improve this? There seems to be no in-memory cache for each VM. Do you plan to add one or are there some alternatives?

**Comment by stickfigure** [comment]
I suspect v5 cache behavior will be identical to v4. It depends on how old your v4 is. I would certainly upgrade though, v4 is old.

v6 has a pluggable cache implementation. Conceivably you could do anything with that.

Clustered in-VM caching is extraordinarily hard to get right. I babysat a number of clustered JBoss instances many years ago and the cache was always a PITA. I don't even know how you'd go about implementing it on GAE Standard (no multicast).
