### ISSUE TITLE
NOT_EQUAL not working

### ISSUE THREAD

**Issue by bhuvaneshwariarkala** [objectify/objectify#372]
Hello Team,

I  am using Query to search for the entity which is not equal to "deviceId" which is string.

Filter idFilter =
				new FilterPredicate("deviceId",
						FilterOperator.NOT_EQUAL,
						deviceId); 

ofy().load().type(entity).filter(idFilter)

This is returning null values, Can you please suggest what wrong iam doign here

Thanks,
Bhuvana

**Comment by stickfigure** [comment]
This kind of question is really best for stackoverflow, where many more people can respond. Is `idFilter` an indexed field? Also, just in case - it can't be an `@Id` field.
