### ISSUE TITLE
Lombok dose not currently support JDK10, making Objectify not support JDK10

### ISSUE THREAD

**Issue by lesv** [objectify/objectify#378]
See https://stackoverflow.com/questions/50249884/typetags-error-in-java-jdk10
and https://github.com/rzwitserloot/lombok/issues/1572 for additional information.

**Comment by lesv** [comment]
And https://github.com/rzwitserloot/lombok/issues/1651 says that it's fixed in an "Edge" release.

**Comment by stickfigure** [comment]
This doesn't quite make sense. Objectify doesn't include lombok as a dependency, it's `<provided>`, ie only used when building Objectify. Are you saying that the lombok-generated code is somehow incompatible with JDK10? That's not with the lombok issue indicates, and it would be pretty shocking.

**Comment by tangiel** [comment]
Builds fail because Lombok depends on a class in javac code that no longer appears to exist. It's not an issue of runtime.

**Comment by lesv** [comment]
I think it's the generated code.

**Comment by lesv** [comment]
The problem is that they misspelled the error.  
```
Fatal error compiling: java.lang.ExceptionInInitializerError: com.sun.tools.javac.codeTypeTags 
```
should be `com.sun.tools.javac.code.TypeTags`

**Comment by stickfigure** [comment]
I looked closer. That guy's pom specified Objectify 5.1.5, which pre-dates adding lombok to Objectify. If it's something to do with lombok, it isn't coming from Objectify.

**Comment by stickfigure** [comment]
Also: I am very doubtful that there's an issue with the post-lombok generated code; certainly it would never reference com.sun.tools.javac. This looks like something in the dependency graph is declaring lombok without `<scope>provided</scope>`. It isn't Objectify :-/

**Comment by stickfigure** [comment]
I'm going to close this issue for now, if we find another reason to suspect Objectify, I'm happy to re-open it.

**Comment by tangiel** [comment]
Yeah, sorry. It was another dependency (jgeohash-core).

**Comment by stickfigure** [comment]
No worries, glad it's all sorted
