### ISSUE TITLE
set DatastoreServiceConfig param

### ISSUE THREAD

**Issue by achecinski** [objectify/objectify#379]
Hi,

I would like to define a DatastoreServiceConfig param.
The DatastoreServiceConfig is set in ObjectifyFactory.
Should I extend ObjectifyFactory to add the param?
If so, how can I inject my factory in Objectify.
How can I do it otherwise?

Thanks for you help.

**Comment by achecinski** [comment]
Find a way to do it.
I extended the ObjectifyFactory and used ObjectifyService.setFactory() to inject it.

**Comment by stickfigure** [comment]
Exactly right - glad you found it!
