### ISSUE TITLE
@Index

### ISSUE THREAD

**Issue by bhuvaneshwariarkala** [objectify/objectify#381]
Hello Team,

I have an entity with 3 fields and I have indexed all of them.

@Entity
public class UserMapper{
	
	@Id@Index
	public String id = UUID.randomUUID().toString();
	
	@Index
	public String email;
	
	@Index
	public String userToken;
	
	@Index
	public String deviceId;

}

But in server userToken field is showing as not indexed, and I could not search using that field.
It is showing "you can only sort indexed properties"
What wrong I am doing here. Please can someone help me?

Thanks,
Bhuvana

**Comment by stickfigure** [comment]
If you are getting an error message, you are probably trying to perform a multi-property query (say, a filter on one property and a sort on another). These need to be configured in datastore-indexes.xml. Not sure which version of Objectify you're on but here's the Cloud Datastore docs:

https://cloud.google.com/appengine/docs/standard/java/datastore/indexes

There is a difference between multiproperty indexes and single property indexes. The `@Index` annotation creates single property indexes, which are established with the entity is saved (not via code inspection), and if missing, entities will simply not show up in the search results.

Also note that `@Index` on an `@Id` field has no effect. You don't index ids, they're part of the key.

**Comment by bhuvaneshwariarkala** [comment]
Hi,

I am doing single key search only.
<img width="693" alt="screen shot 2018-05-28 at 10 00 57 pm" src="https://user-images.githubusercontent.com/29437769/40623081-a6aade98-62c2-11e8-9ecc-5b9b6345a1c6.png">


TokenMapper user = DBService.getInstance().getByKind(TokenMapper.class, "userToken",
						userTokenMapper.userToken)
And one more thing in the Database itself it is(ie) userToken) not showing as Indexded field.Please see the screenshot attached.

**Comment by stickfigure** [comment]
Keep in mind that you need to explicitly save the entity after you add the `@Index` to your code. If you save the entity, then add `@Index` and deploy your code, nothing changes in the datastore; you must load+save it again to alter the data.

My guess is that this is what you are seeing, but I'm not really an expert in behavior of Google's datastore console.  Presumably if any one entity has been indexed, it treats the whole column as indexed.

**Comment by bhuvaneshwariarkala** [comment]
I am doing the  same load + save

**Comment by stickfigure** [comment]
In that case, I'm wildly guessing that the google console UI figures out what is/isn't indexed when it calculates statistics (nightly batch, IIRC). Maybe it will 'figure it out' in a day or two.

At this point we're out of my depth - this is a question for the team at Google working on the console. If you doubt that the field is getting indexed, try to run a query on it in code. If it works (and it will), it's indexed.
