### ISSUE TITLE
Joda Time 2.10.0

### ISSUE THREAD

**Issue by elharo** [objectify/objectify#386]
Objectify 5 depends on Joda Time 2.7.0
Objectify 5 depends on Joda Time 2.9.9

Both should be upgraded 2.10.0

**Comment by stickfigure** [comment]
It's an optional dependency. In order to include it in your project, you need to specify it in your pom along with a version number. Unless there is a compatibility issue, it really doesn't matter what version Objectify specifies. Do you have reason to believe there is a compatibility issue?

**Comment by elharo** [comment]
I'm seeing it pulled into the classpath without an explicit dependency in my code. I'll investigate further. 

Also, we're trying to cleanup dependency issues across the whole App Engine tree: google-cloud-java, dataflow, GRPC, etc. so we can converge onto reliable versions.

**Comment by stickfigure** [comment]
From the pom:

```xml
		<dependency>
			<groupId>joda-time</groupId>
			<artifactId>joda-time</artifactId>
			<version>2.9.9</version>
			<scope>compile</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.joda</groupId>
			<artifactId>joda-money</artifactId>
			<version>0.10.0</version>
			<scope>compile</scope>
			<optional>true</optional>
		</dependency>
```
