### ISSUE TITLE
When making call to Objectifyservice.ofy through Thread or scheduler Objectify Context error occurs

### ISSUE THREAD

**Issue by nileshvid** [objectify/objectify#388]
I have already registered ObjectifyFilter 
@Bean
public FilterRegistrationBean someFilterRegistration() {
FilterRegistrationBean registration = new FilterRegistrationBean();
registration.setFilter(objectifyFilter());
registration.addUrlPatterns("/*");
registration.setName("ObjectifyFilter");
registration.setDispatcherTypes(DispatcherType.REQUEST,DispatcherType.INCLUDE,DispatcherType.FORWARD);
return registration;
}
When I am making any rest call to access this service it works fine.
But as I am making parallel calls through thread or calling it through scheduler I am getting this error.

**java.lang.IllegalStateException: You have not started an Objectify context. You are probably missing the ObjectifyFilter. If you are not running in the context of an http request, see the ObjectifyService.run() method.
        at com.googlecode.objectify.ObjectifyService.ofy(ObjectifyService.java:44) ~[objectify-5.1.21.jar!/:?]
        at com.nviz.rategate.service.OfyService.ofy(OfyService.java:23) ~[classes!/:1.0.0-SNAPSHOT]**

**Comment by stickfigure** [comment]
Like most database libraries, Objectify maintains transaction context in a thread local. To set up and tear it down, each thread using Objectify requires either 1) the `ObjectifyFilter` or 2) to be wrapped in `ObjectifyService.run()` (or `ObjectifyService.begin()` + `close()`).

Take a look at the code for `ObjectifyFilter` and do the same thing in your thread. It's nearly a one-liner.

**Comment by vidyarthitech2tech** [comment]
Thanks. It worked

**Comment by nileshvid** [comment]
Thanks. It worked
