### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by bhuvaneshwariarkala** [objectify/objectify#392]
Hello team,

I have one requirement. I have around 2000 rows in one entity. And it is taking around 20secs to read all the rows of the entity.

This is the query Iam using.
 ofy().load().type(entity)
				.filter(fieldName, value1)
				.filter(fieldName1, value2)
				.filter(rangeFilter).offset(offset).limit(limit).list();

But I want to fetch them in 5 secs due to time consistency.Is there better way, can you please provide any better solution?

Thanks,
Bhuvana

**Comment by stickfigure** [comment]
This issue tracker is really not a good place for questions like this - I would try stackoverflow or the objectify google group. Large offsets will slow your query down, but even without that, the datastore just isn't fast at loading data in bulk. Generally try to structure your data in fewer, coarser entities. It's not possible for me to give you specific advice without knowing anything about your app.
