### ISSUE TITLE
com.google.appengine.api.datastore.TransactionImpl cannot be cast to com.googlecode.objectify.cache.CachingTransaction

### ISSUE THREAD

**Issue by NicolaSpreafico** [objectify/objectify#395]
Hi,
I'm getting the error used in title with a Lock mechanism built on Datastore, here is the details:

The application is running on an App Engine Standard environment (Java8), using this version:
```
<dependency>
            <groupId>com.googlecode.objectify</groupId>
            <artifactId>objectify</artifactId>
            <version>5.1.13</version>
        </dependency>
```

To avoid write concurrency on the same object (there is a processing flow which read an object from an outside datasource and process the data), I built a simple "lock" mechanism. I save in the datatore an entity which contains who is locking the object, the identifier of the object and when the object was locked.

```
@Entity(name = "Lock")
public class Lock {
    @Id
    private String identifier;

    private Date date;

    private String holder;
}
```

With this container I can produce an error if a second actor try to edit the object, while a first processing flow is still running on it.

Here is the manager which handle the locking mechanism:
```
public static void lock(final String identifier, final String holder) {
    VoidWork work = new VoidWork() {
        @Override
        public void vrun() {
            Key<Lock> key = Key.create(Lock.class, identifier);
            Lock lock = ofy().load().key(key).now();

            if (lock == null) {
                lock = new Lock(identifier, holder);
                ofy().save().entity(lock);
            } else {
                throw new LockException(lock.getDate(), lock.getIdentifier());
            }
        }
    };

    ofy().transact(work);
}

public static void unlock(final String identifier, final String holder) {
    VoidWork work = new VoidWork() {
        @Override
        public void vrun() {
            Key<Lock> key = Key.create(Lock.class, identifier);
            Lock lock = ofy().load().key(key).now();
            
            if (lock != null)  {
                ofy().delete().entity(lock);
            }
        }
    };

    ofy().transact(work);
}
```

Executing the flow I got this error:
```
java.lang.ClassCastException: com.google.appengine.api.datastore.TransactionImpl cannot be cast to com.googlecode.objectify.cache.CachingTransaction
    at com.googlecode.objectify.cache.CachingAsyncDatastoreService$5.trigger(CachingAsyncDatastoreService.java:441)
    at com.googlecode.objectify.cache.TriggerFuture.isDone(TriggerFuture.java:87)
    at com.googlecode.objectify.cache.TriggerFuture.get(TriggerFuture.java:102)
    at com.googlecode.objectify.impl.ResultAdapter.now(ResultAdapter.java:34)
    at com.googlecode.objectify.util.ResultWrapper.translate(ResultWrapper.java:22)
    at com.googlecode.objectify.util.ResultWrapper.translate(ResultWrapper.java:10)
    at com.googlecode.objectify.util.ResultTranslator.nowUncached(ResultTranslator.java:21)
    at com.googlecode.objectify.util.ResultCache.now(ResultCache.java:30)
    at com.googlecode.objectify.util.ResultWrapper.translate(ResultWrapper.java:22)
    at com.googlecode.objectify.util.ResultWrapper.translate(ResultWrapper.java:10)
    at com.googlecode.objectify.util.ResultTranslator.nowUncached(ResultTranslator.java:21)
    at com.googlecode.objectify.util.ResultCache.now(ResultCache.java:30)
    at com.noovle.caranalyser.upload.manager.lock.LockManager.executeLock(LockManager.java:78)
```

Am I coding something wrong or this is an unexpected behaviour?

Please note this: the implementation works fine under light load, like during test on local environment or else in the online environment with few requests. This particular error was thrown during heavy load (the application scaled up to 35~40 instances)

**Comment by stickfigure** [comment]
There's nothing obviously wrong here and this is not expected behavior. The issue is elsewhere. Are you doing any manual transaction management anywhere?

The cache layer (`CachingAsyncDatastoreService`) expects that all datastore access goes through it. Critically, when a transaction is started, the cache layer provides a wrapper for the `Transaction` object so that it can associate some important state with the txn. What's happening here is that a raw, unwrapped datastore Transaction is being passed to the `CachingAsyncDatastoreService.put()` method. The `put()` method only accepts `Transaction`s that were created by calling `CachingAsyncDatastoreService.beginTransaction()`.

If you just have Objectify manage transactions for you, this should never be a problem. What's going on in `LockManager.executeLock()`?

**Comment by NicolaSpreafico** [comment]
Sorry, my mistake. The line `LockManager.executeLock(LockManager.java:78)` is indeed the `unlock` method from the source I gave you. I simplified the code to focus on the part which interact with Objecitfy, I forgot to rename the method from the stacktrace. Method name aside, the current implementation is the one already provided.

The transaction management is all here, creating the work and execute the transact method. There is no other management.

**Comment by stickfigure** [comment]
Are you calling `ofy().cache(false)` in your code anywhere around here? If so, what does that look like? I'm trying to find a usage pattern that could logically produce this behavior.

**Comment by NicolaSpreafico** [comment]
No, I'm not using `.cache()` method at all. The code is simple as you are looking for. 
After upgrading version and using directly static method `ofy()` (see #396) I launched 2 times the procedure under heavy load and I did not get this error at all.

**Comment by stickfigure** [comment]
I suspect this has to do with some sort of incorrect usage of an `ofy` variable. Glad it's working now!
