### ISSUE TITLE
The referenced transaction has expired or is no longer valid.

### ISSUE THREAD

**Issue by NicolaSpreafico** [objectify/objectify#396]
Hi,
I'm getting the error used in title with a transaction which creates multiple entities at once.

The application is running on an App Engine Standard environment (Java8), using this version:
```
<dependency>
            <groupId>com.googlecode.objectify</groupId>
            <artifactId>objectify</artifactId>
            <version>5.1.13</version>
        </dependency>
```

The transaction content is very simple:
```
final Objectify ofy = ofy().consistency(Consistency.STRONG);
        ofy.transact(new VoidWork() {
            @SuppressWarnings("synthetic-access")
            @Override
            public void vrun() {
                List<RelationshipMap> holders = createContainers(object);
                ofy().save().entities(holders).now();
            }
        });
```

The "container" object is a simple bean which declare some variables:
```
@Entity(name = "RelationshipMap")
public class RelationshipMap {
    static final Key DEFAUL_PARENT = KeyFactory.createKey("Ancestor", "RelationshipMap");

    @Parent
    private Key parent = DEFAUL_PARENT;

    @Id
    private String name;

    @Index
    private String referredEntityName;

    @Index
    private Long referredEntityId;

    @Index
    private String holderEntityName;

    @Index
    private Long holderEntityId;

    @Unindex
    private String holderEntityField;
}
```

This is the full stacktrace I got executing the transaction:
```
java.lang.IllegalArgumentException: The referenced transaction has expired or is no longer valid.
    at com.google.appengine.api.datastore.DatastoreApiHelper.translateError(DatastoreApiHelper.java:53)
    at com.google.appengine.api.datastore.DatastoreApiHelper$1.convertException(DatastoreApiHelper.java:136)
    at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:109)
    at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:93)
    at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:93)
    at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:93)
    at com.googlecode.objectify.cache.TriggerFuture.get(TriggerFuture.java:100)
    at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:93)
    at com.googlecode.objectify.util.FutureHelper.quietGet(FutureHelper.java:29)
    at com.googlecode.objectify.impl.TransactionImpl.commit(TransactionImpl.java:72)
    at com.googlecode.objectify.impl.TransactorNo.transactOnce(TransactorNo.java:123)
    at com.googlecode.objectify.impl.TransactorNo.transactNew(TransactorNo.java:97)
    at com.googlecode.objectify.impl.TransactorNo.transact(TransactorNo.java:85)
    at com.googlecode.objectify.impl.ObjectifyImpl.transact(ObjectifyImpl.java:179)
    at it.noovle.ape.manager.relationship.RelationshipMapManager.onCreate(RelationshipMapManager.java:55)
```

Please note this: the implementation works fine under light load, like during test on local environment or else in the online environment with few requests. This particular error was thrown during heavy load (the application scaled up to 35~40 instances)

**Comment by stickfigure** [comment]
This is _probably_ caused by some sort of mistake using the wrong Objectify object. There's nothing obviously wrong with the code here but it's risky to hold an Objectify reference (ie create an `ofy` variable) instead of always using the static `ofy()` method. If you accidentally use the wrong ofy object in the wrong context, you can pretty easily get this kind of behavior. `ofy()` always does the right thing.

I would look around your code for places you should be calling `ofy().blah()` instead of `ofy.blah()`.

FWIW Consistency.STRONG is the default so that call does nothing.

Also, I would upgrade to the latest v5 version (v5.1.22). I don't think it affects this issue but 5.1.13 is a couple years old.

**Comment by stickfigure** [comment]
Yes, if you do this, you'll have to call .cache() every time.

It's certainly possible to take a reference to the Objectify instance (with its cache/consistency/etc state) and hold on to it briefly. The problem is that if you make a mistake and use the wrong instance in the wrong place, you get this issue. You can go through your code with a comb and find the problem, or just hit the problem with a hammer and get rid of all the instance references.

In practice changing the `cache()` or `consistency()` setting should be a rare occurrence and should probably stand out in the code; it should look better duplicating the call than holding object references. A lot of `cache()` tweaking is a code smell and you can get yourself into consistency issues pretty easily if you aren't very careful.

**Comment by NicolaSpreafico** [comment]
After upgrading version and using directly static method `ofy()` I launched 2 times the procedure under heavy load and I did not get this error at all. I have already scheduled others tests under heavier load to stress the application as possible, maybe in that case the error will pop out again, I hope not.

I understood that creating a variabile which holds the `ofy` instance can produce a bad behaviour:
```
final Objectify ofy = ofy().consistency(Consistency.STRONG);

        ofy.transact(new VoidWork() {
            @SuppressWarnings("synthetic-access")
            @Override
            public void vrun() {
                ofy.doStuff();
                ofy.doAnotherStuff();
                ofy.doOtherStuff();
            }
        });
```

Your suggestion, If I need to configure specific settings to the instance, it is better to replicate the code every time I access the `ofy()` instance (let's imagine only for this example that I need to configure `cache` and `consistency`)
```
        ofy().cache(false).consistency(STRONG).transact(new VoidWork() {
            @Override
            public void vrun() {
                ofy().cache(false).consistency(STRONG).doStuff();
                ofy().cache(false).consistency(STRONG).doAnotherStuff();
                ofy().cache(false).consistency(STRONG).doOtherStuff();
            }
        });
```

About this case, only to improve maintainability and readability, something like this make sense?
```
        myOfy().transact(new VoidWork() {
            @Override
            public void vrun() {
                myOfy().doStuff();
                myOfy().doAnotherStuff();
                myOfy().doOtherStuff();
            }
        });

       private static Objectify myOfy() {
              return ofy().cache(false).consistency(STRONG);
       }
```

**Comment by stickfigure** [comment]
Yes, you pretty much have it. That first example is *definitely* wrong and will cause all sorts of problems; you are using an Objectify instance in two different transaction scopes. While you can do that, it will not have the effect you think (you will not actually be using a transaction). The second two examples will work.

**HOWEVER.**

`consistency(STRONG)` is totally pointless; that's the default. This code has no effect.

`cache(false)` as a default is probably going to have bad effects - if you run this way (only enabling cache periodically), then you will almost certainly see a stale cache. When you issue (non-cache) save operations, it will not flush the cache entries... so any calls that actually do use the cache will see stale entries.

Caching only works if you use it by default, and the `cache(false)` option exists for the rare occasion that you want to read a bunch of data without contaminating the cache. You can't reasonably use a cache the other way 'round. If you don't want caching, don't use the `@Cache` annotation.
