### ISSUE TITLE
Issue with objectify save

### ISSUE THREAD

**Issue by anmol1vw13** [objectify/objectify#400]
I have a usecase wherein I save an entity for the first time and a second after saving it I fetch it, update it a bit and save it in batch along with two other entites (different 'kinds'). In a few cases (10 out of 50K), the update to datastore is ignored. I mean, it's there in the objectify cache but the change didn't happen in datastore. How I am able to justify the above, is because after the save, I fetch it again after a second and I'm able to see it.

PS: I also use .now() while saving. This shouldn't happen when now() is used right?
I have also post a question on stackoverflow regarding [this.](https://stackoverflow.com/questions/51877432/issue-with-objectify-save)
@stickfigure Could you please help me out?

**Comment by stickfigure** [comment]
Are you loading it with a query (as opposed to getting it by key)? Perhaps you are seeing the eventual consistency behavior of the datastore?
