### ISSUE TITLE
Caching Implementation With Objectify v6+

### ISSUE THREAD

**Issue by PhilippeBoisney** [objectify/objectify#401]
I've recently migrated to Objectify v6+. Everything works fine, except Memcache (nothing saved inside).
Here is how I've configured Objectify : 
```
public class BootstrapperServlet implements ServletContextListener {

	@Override
	public void contextDestroyed(ServletContextEvent sce) { }

	@Override
	public void contextInitialized(ServletContextEvent sce) { 
	
		ObjectifyService.init();
		ObjectifyService.register(MyEntity1.class);
                 ObjectifyService.register(MyEntity2.class);
                 ...       
	}
}
```
All my entities are marked with `@Entity` annotation.

I read the documentation, and it seems that I have to pass to `ObjectifyService` an `ObjectifyFactory` with a [spymemcached](https://github.com/couchbase/spymemcached) configured.

`ObjectifyService.init(new ObjectifyFactory(mySpymemcachedClient));`

The problem is I can't manage to create this `mySpymemcachedClient` object... Do you have any sample showing how to achieve that properly @stickfigure ?

**Comment by stickfigure** [comment]
There is an example in Objectify's test harness:

https://github.com/objectify/objectify/blob/master/src/test/java/com/googlecode/objectify/test/util/LocalMemcacheExtension.java

It's just this:

`final MemcachedClient client = new MemcachedClient(new InetSocketAddress("localhost", 11211));`

**Comment by PhilippeBoisney** [comment]
Perfect ! Thanks !
