### ISSUE TITLE
Namespaces in Objectify v6

### ISSUE THREAD

**Issue by UweTrottmann** [objectify/objectify#402]
[The old way](https://github.com/objectify/objectify/issues/208) of using namespaces with Objectify seems to no longer work in v6 (at least in my project).

If I understand the code correctly ([the docs](https://cloud.google.com/appengine/docs/standard/java/multitenancy/) and [example](https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/appengine-java8/multitenancy) for multitenancy/namespaces are outdated) switching namespaces using `com.google.appengine.api.NamespaceManager` is ignored when using the new Google Cloud Java library that Objectify 6 uses.

It appears the new library [reads the namespace once](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-clients/google-cloud-datastore/src/main/java/com/google/cloud/datastore/DatastoreOptions.java#L161-L171) using `NamespaceManager.get()` when building `DatastoreOptions`.

However, [based on their tests](https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-clients/google-cloud-datastore/src/test/java/com/google/cloud/datastore) and [example](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-examples/src/main/java/com/google/cloud/examples/datastore/DatastoreExample.java) it looks like there is now a namespace option for each operation:
- when creating entity keys: `datastore.newKeyFactory().setNamespace(namespace)` [impl. by BaseKey.Builder](https://googlecloudplatform.github.io/google-cloud-java/google-cloud-clients/apidocs/com/google/cloud/datastore/BaseKey.Builder.html#setNamespace-java.lang.String-)
- when building a query: `Query.newEntityQueryBuilder().setNamespace(namespace)` [impl. by StructuredQuery.Builder](https://googlecloudplatform.github.io/google-cloud-java/google-cloud-clients/apidocs/com/google/cloud/datastore/StructuredQuery.Builder.html#setNamespace-java.lang.String-)

If this is the way how namespaces are handled going forward, is it feasible for Objectify to expose this?

(I already had a look and it is probably easy to add a namespace option on [QueryDef](https://github.com/objectify/objectify/blob/master/src/main/java/com/googlecode/objectify/impl/QueryDef.java). But I'm unsure how to allow setting a namespace for entity keys.)

For now, to use namespaces one can simply stick with v5.

Thanks for this great library!

**Comment by nileshvid** [comment]
For v6 you can try 

DatastoreOptions ds = DatastoreOptions.
ds = ds.toBuilder().setNamespace("uat").build();
Datastore dss = ds.getService();
ObjectifyService.init(new ObjectifyFactory(dss));

**Comment by UweTrottmann** [comment]
@nileshvid Thanks, sorry I did not point this out explicitly: this requires re-building the factory every time the namespace changes. However, my use case requires switching namespaces frequently (multi-user).

**Comment by stickfigure** [comment]
There's two options here:

1) Do what Ofy5 did, but create our own NamespaceManager thread local since the SDK doesn't provide one
2) Add a `@Namespace` field to entities (along with `@Parent` and `@Id`).

These aren't mutually exclusive; we could have both but wth one overriding the other. What do you think?

**Comment by UweTrottmann** [comment]
A custom `NamespaceManager` would likely make migration easy.

However, a `@Namespace` field would probably allow mixing multiple entities with different namespaces during a single operation. This is closer to what the new Datastore API is doing (setting a namespace while building a key) and so preferable to me.

Though, without a `NamespaceManager` I am unsure how queries determine the namespace to search in?

Regarding precedence if doing both: I guess a namespace set on an entity should override any more global namespace, like set through a `NamespaceManager`?

**Comment by DmytroSydorenko** [comment]
It would be very flexible to have possibility to set namespace while building query:
`ofy().namespace("<NAMESPACE>").save()...`

**Comment by jdamour98** [comment]
Any updates?

**Comment by stickfigure** [comment]
This is now available in Objectify 6.0.4.

I took the "all of the above" approach - `NamespaceManager` plus a `@Namespace` annotation.

Documentation is here: https://github.com/objectify/objectify/wiki/Namespaces
