### ISSUE TITLE
Custom com.googlecode.objectify.cache.MemcacheService putAll() gives null values

### ISSUE THREAD

**Issue by ykayacan** [objectify/objectify#408]
Version: 6.0.2

I implemented a custom com.googlecode.objectify.cache.MemcacheService and passed it into ObjectifyFactory. However when I saved a cache enabled entity, map.values() of "public void putAll(final Map<Key, Object> map)" give null.

Example code:

```java
@Cache
@Entity // omitted getters
public class Demo {
  @Id private long id;
  private String text;

  public Demo() {
  }

  public Demo(long id, String text) {
    this.id = id;
    this.text = text;
  }
}

Demo demo = new Demo(1, "hello");
ofy().save().entity(demo).now();
```

**Comment by stickfigure** [comment]
This is basically the correct behavior. The cache is a read-through cache. When you save data, the cache entry is cleared.
