### ISSUE TITLE
Using Objectify v5 and v6 at once

### ISSUE THREAD

**Issue by nbali** [objectify/objectify#411]
We have run into scenarios multiple times when we wanted to use Objectify v5 and v6 together. For example in Cloud Dataflow we can't use v5, but we want to modify those entities with a GAE app, where for some other kinds - that won't be used outside of that app - we find v5 still a better fit. So we would like to have v5 handle some classes, v6 others.

The packages are the same right now, so the class names would collide. What I would like to do is to change that. Just like commons-lang vs commons-lang3.

The concept of v6 was obviously to completely abandon v5 - I assume that is why it was completely refactored, instead extracted into objectify-shared, objectify-gae, objectify-cloud - but IMO it should be allowed to use them together.

So I propose to rename the packages from `com.googlecode.objectify.` to `com.googlecode.objectify5.`.

**Comment by nbali** [comment]
fyi @stickfigure @fpeter8 @ttozser @gabor-farkas

**Comment by nbali** [comment]
Well our use-case comes from the fact that we want to map the same datastore entity to the same class with v5 (gae) and v6 (dataflow). I would have created the `-shared` for that, but that part is over.

Your ultimate goal seems to be is to move everybody to v6. Well the gap is too big for us probably on _every_ GAE project we have so we won't do it until Google forces us by shutting down something that is necessary for it.

Also I can't call a migration problematic, which requires a simple `.objectify.` to `.objectify5.` replace. That is nothing compared to even previous breaking changes as far as I remember Objectify had, but obviously eventually it's your call. We don't mind if you say it's not going to happen, but then we go with a fork, because we _need_ it (because the current workaround - to use GSON and store the whole entity as a text - works, but  it's ugly as f*ck).

**Comment by nbali** [comment]
Well if you would maintain it - so it would stay in this repo just on a different branch -, then it wouldn't be a fork at all so that is kinda obvious who can be the maintainer of a *fork* :). Anyway we will have to discuss resourcing for that internally first.

**Comment by stickfigure** [comment]
Totally happy to keep it on a branch! And I can put it in maven central.

**Comment by nbali** [comment]
What branch, and what versionning convention do you have in mind?

**Comment by stickfigure** [comment]
This seems to have died out. Going to close this issue as part of housecleaning, if folks want it reopened, we can talk.
