### ISSUE TITLE
Request for fixing doc: Query objects are not asynchronous

### ISSUE THREAD

**Issue by carbon-twelve** [objectify/objectify#413]
Hi there,

I found a little miscenception in the User's Guide while I was reading the section of Queries and Indexes.
It states that
>  Query result objects (Iterable<?>, List<?>, Ref<?>) are inherently asynchronous.

but IIRC the behavior of Query objects is **NOT asynchronous** but **lazy**. For example, `QueryResultIterable#iterator` begins the query operation and itself blocks until it obtains the results to be iterated.
If they were asynchronous, it would be creation of a `QueryResultIterable` object instead of call of `iterator` method when the query operation is kicked.
Would be great if someone more familiar with Objectify could confirm this and rewrite the part mentioned above.

**Comment by stickfigure** [comment]
The answer to this is a bit complicated.

In Objectify v5, List and friends are indeed asynchronous. Calling `ofy()...list()` kicks off an asynchronous query in the backend (generating a QueryResultIterable) which is fully materialized when you try to access the contents of the list.

In Objectify v6, we've preserved all of the inherent future-based behavior down to Google's API, which does not (currently) support async behavior. When they add futures to the gcloud jar, it will be easy to wire them up. Until then nothing in v6 is really async, but you're future-proofed if you write your code that way.

**Comment by stickfigure** [comment]
No problem! Cheers.
