### ISSUE TITLE
Will Objectify adapt the fact that Cloud Firestore Datastore mode queries always are strongly consistent 

### ISSUE THREAD

**Issue by chrisbbe** [objectify/objectify#416]
According to Google, all Datastore users will be automatically migrated to Cloud Firestore in Datastore mode which will utilize the new storage layer provided with Firestore, which is always strongly consistent.

**Will Objectify in further releases support queries without ancestor?**

**Comment by stickfigure** [comment]
I can't think of any reason why Objectify would require changes to support this; Objectify itself doesn't restrict query behavior. Any limits are enforced at some lower level - either the google-provided library that Objectify is built on, or maybe something deeper (I don't know).

If you try it and get an error, post a stacktrace. If the source from something `com.googlecode.objectify` then it's a bug in Objectify I can fix. If it's something `com.google` then we have to lean on Google.
