### ISSUE TITLE
Description for unit testing / DatastoreExcepion Unauthenticated in v6

### ISSUE THREAD

**Issue by Rhobal** [objectify/objectify#417]
Please add a Wiki entry on how to set up unit testing.
I have a working setup for v5 where I
* Register classes and translators in `@BeforeClass`
* Start a session with `begin()` in `@Before` and close the session in `@After`
* Close and restart the session after joining parallel tasks

However, with v6, I get a "DatastoreException: Unauthenticated, code=UNAUTHENTICATED" whenever I try to access the datastore

**Comment by zmeggyesi** [comment]
I happened to run into the same thing while building a new project. My setup involves using a custom `ObjectifyFactory` instance passed into the service to connect to the in-memory datastore emulator. See below:

```
@BeforeAll
	public static void setupTestEnvironment() throws IOException, InterruptedException {
		helper.start();

		Datastore datastore = helper.getOptions().getService();
		ObjectifyFactory factory = new ObjectifyFactory(datastore);
		ObjectifyService.init(factory);

		// register classes
	}
```

Where the `helper` is just the `LocalDatastoreHelper` from the Cloud SDK.

Can you see if this works for your setup too?

**Comment by Rhobal** [comment]
Thanks! I managed to get my tests running by copying the LocalDatastoreExtension and the ObjectifyExtension from the objectify, and I removed the LocalDatastoreServiceTestConfig from the LocalServiceTestHelper. 
Can't say I particularly like the situation, as I still have the LocalServiceTestHelper from com.google.appengine for the task queue config, evironment etc, while the datastore helper is from com.google.cloud but I'm happy I at least got some tests running

**Comment by Rhobal** [comment]
Edited the wiki

**Comment by stickfigure** [comment]
FWIW Objectify doesn't directly interact with the task queue in any way; if you're using the old task queue API (as opposed to the new Cloud Tasks API), you'll need the old local test helpers.

The Objectify junit extensions are the canonical examples of how to set up test cases. You can also use them as-is.

**Comment by Rhobal** [comment]
Thats what I do, I kept the old helpers for task queue and have the new extensions for local datastore & Objectify
