### ISSUE TITLE
AppEngine - When SOCKET_CONNECT_COUNT quota is exhausted, Objectify just hangs with no error logging

### ISSUE THREAD

**Issue by branks** [objectify/objectify#418]
Using Objectify 6 in AppEngine
When SOCKET_CONNECT_COUNT quota is all used up, any calls to Objectify that should go via the datastore never return, however memcache calls do. A DeadlineExceededError is then thrown against any request that was doing a datastore query but with no notification of why the query was hanging

As a side question, we were finding that our SOCKET_CONNECT_COUNT default allowance of ~3million was being used up fairly fast. Does any call to memcache or datastore use this, and therefore a read actually uses 2 as it's checking firstly the memcache and then the datastore?

**Comment by stickfigure** [comment]
Objectify does not directly connect to Google's services; it uses the low level libraries that Google provides. This is really an issue for the google-cloud-datastore jar team; Objectify doesn't directly do anything socket related.

I'm afraid I don't know the answer to your question. Objectify holds a spymemcached client reference. If you aren't recreating the ObjectifyFactory, it shouldn't open sockets repeatedly.
