### ISSUE TITLE
No API environment is registered for this thread.

### ISSUE THREAD

**Issue by isaacguerreir** [objectify/objectify#420]
I'm getting trouble trying to run a query inside a scheduler in Spring. The error that appear is this:

**No API environment is registered for this thread.**

I'm using ObjectifyService.run() to use objectify outside context. Why I'm missing?

**Comment by stickfigure** [comment]
That's what happens when you try to use the appengine apis outside of GAE Standard.

If you want to work outside GAE Standard, maybe you want Objectify6 which works with the google-cloud-java artifact and the http interface to the datastore?
