### ISSUE TITLE
Update google-cloud-datastore to 1.74.0

### ISSUE THREAD

**Issue by elharo** [objectify/objectify#421]
This critical dependency is very far behind HEAD and pulls inh lots of other outdated dependencies:

```
		<dependency>
			<groupId>com.google.cloud</groupId>
			<artifactId>google-cloud-datastore</artifactId>
			<version>1.16.0</version>
		</dependency>
```

Truth could also use an update.

**Comment by elharo** [comment]
This isn't just a quick one line change to pom.xml but is still worth doing.

[ERROR] /usr/local/google/home/elharo/objectify/src/main/java/com/googlecode/objectify/impl/ProjectionQueryResults.java:[11,1] com.googlecode.objectify.impl.ProjectionQueryResults is not abstract and does not override abstract method getMoreResults() in com.google.cloud.datastore.QueryResults
[ERROR] /usr/local/google/home/elharo/objectify/src/main/java/com/googlecode/objectify/impl/HybridQueryResults.java:[22,8] com.googlecode.objectify.impl.HybridQueryResults is not abstract and does not override abstract method getMoreResults() in com.google.cloud.datastore.QueryResults
[ERROR] /usr/local/google/home/elharo/objectify/src/main/java/com/googlecode/objectify/impl/StuffingQueryResults.java:[14,1] com.googlecode.objectify.impl.StuffingQueryResults is not abstract and does not override abstract method getMoreResults() in com.google.cloud.datastore.QueryResults
[ERROR] /usr/local/google/home/elharo/objectify/src/main/java/com/googlecode/objectify/impl/KeyQueryResults.java:[12,1] com.googlecode.objectify.impl.KeyQueryResults is not abstract and does not override abstract method getMoreResults() in com.google.cloud.datastore.QueryResults

**Comment by stickfigure** [comment]
Thanks, updated to 1.74.
