### ISSUE TITLE
@OnLoad not working

### ISSUE THREAD

**Issue by BrentOliverBC** [objectify/objectify#423]
Came across an issue while trying to get some of our entities to work with objectify v6 specifically the @OnLoad annotation. I see the annotation being loaded and added to the list in ClassPopulator but it seems to never be called upon load of the entity. Running the same unit test using v5 vs v6 yields a failure in v6.

**Comment by stickfigure** [comment]
Can you construct a test case? All these pass:

https://github.com/objectify/objectify/blob/master/src/test/java/com/googlecode/objectify/test/LifecycleTests.java
https://github.com/objectify/objectify/blob/master/src/test/java/com/googlecode/objectify/test/LifecycleTests2.java
https://github.com/objectify/objectify/blob/master/src/test/java/com/googlecode/objectify/test/LifecycleTests3.java

What isn't covered?

**Comment by BrentOliverBC** [comment]
Did not see that we needed to add `ofy.clear()` in V6 for our unit tests. Working now.

Thank you!
