### ISSUE TITLE
Embedded Entity is empty

### ISSUE THREAD

**Issue by bashoogzaad** [objectify/objectify#426]
I have upgrades from v5 to v6 and now an issue occurs in which the embedded entities of an entity are always empty. I have objects with multiple embedded entities and when I log the output, i only get {“property_map”:{}}. Before I got the correct values, so it worked in v5. 

Is this a known issue in v6?

**Comment by stickfigure** [comment]
No. First I've heard of anything like this. If this is still an issue, we can reopen the issue.
