### ISSUE TITLE
__version__ not populated in v6

### ISSUE THREAD

**Issue by nstuart-idexx** [objectify/objectify#429]
Trying to retrieve the version for an Entity does not currently work

    @Entity
    static class ParentEntity {
        @Id
        String id
        String name
        @IgnoreSave long __version__
    }

__version__ is always 0. We can get the version by accessing __entity_group__ data from Datastore directly:
    
    //this returns what we expect so version field is getting populated
    long entityVersion(Datastore ds, String kind, String name) {
        ds.get(ds.newKeyFactory().setKind('__entity_group__')
                .addAncestor(PathElement.of(kind, name))
                .newKey(1)).getLong('__version__')
    }

But this isn't that great as it's a whole new query back to DS when it should come across in the original query.

There are old posts floating around saying this should work, but assuming thats with versions < 6, which did not use the cloud datastore apis.

**Comment by stickfigure** [comment]
The old datastore API had a special property `__version__` that came back with every entity fetch. The new datastore API doesn't include this data. I'm afraid the only solution I can think of is the one you propose, with the extra fetch.

You could ask Google to bring back the previous behavior in the API?
