### ISSUE TITLE
Read-only transactions not supported?

### ISSUE THREAD

**Issue by zmeggyesi** [objectify/objectify#430]
I see the following in the Datastore documentation:
> Finally, you can use a transaction to read a consistent snapshot of the database. This can be useful when you need multiple reads to render a page or to export data that must be consistent. You can create read-only transaction for these cases.
> 
> Read-only transactions cannot modify entities, but in return, they do not contend with any other transactions and do not need to be retried.
https://cloud.google.com/datastore/docs/concepts/transactions#read-only_transactions

I was wondering if there is support in Objectify for this sort of transaction natively? Or any plans for it?

**Comment by naturalstars** [comment]
I was just looking for this same feature. +1

**Comment by stickfigure** [comment]
Done, will be in the next release.
