### ISSUE TITLE
Objectify and Firestore in Datastore mode

### ISSUE THREAD

**Issue by gpaul-idexx** [objectify/objectify#431]
We're using Firestore in datastore mode, and does indeed tend to be API compatible with datastore and with Objectify, but sometimes the difference leak through. For example, Firestore allows one to issue a query from within a transaction: https://stackoverflow.com/questions/56506230/new-google-cloud-firestore-in-datastore-mode-queries-clarification
but, objectify does not. 

Do you expect objectify to start aligning with Firestore in datastore mode?

**Comment by stickfigure** [comment]
As far as I know there's nothing inside Objectify that would prevent this from working; we just rely on the lower-level API that Google provides and don't try to enforce any limitations on your queries. Try it?

If you get an error, does it come from a `com.google.cloud.*` class? If so, this should be reported to Google.

**Comment by gpaul-idexx** [comment]
Ah, whoops, the error in the case I mentioned is indeed coming from the cloud datastore lib. Thanks for getting back to me.
