### ISSUE TITLE
ofy().namespace(String) is invalid for save(), though it is valid for load()

### ISSUE THREAD

**Issue by fiarabbit** [objectify/objectify#439]
## Version
objectify 6.0.4

## Description
The syntax `ofy().namespace(str)` changes the current namespace temporally for `.load()` but not for `.save()`.
For the `.save()`, the specified namespace `str` is just ignored for `.save()` and the namespace in `NamespaceManager` is used.

## Code to reproduce
```
SomeEntity entity;
ofy().save().namespace("someNamespace").type(SomeEntity.class).entity(entity).now();
ofy().load().namespace("someNamespace").type(SomeEntity.class).first().now(); // <- null
ofy().load().type(SomeEntity.class).first().now(); // <- entity
```

**Comment by stickfigure** [comment]
Fixed
