### ISSUE TITLE
Datastore contention

### ISSUE THREAD

**Issue by LOKESH159** [objectify/objectify#440]
too much contention on these datastore entities. please try again. entity group key. 

I am trying to save multiple entities(20) in a single request. While saving it's throwing contention exception and it's not retrying. I have given the retry limit as 3.

There are no concurrent updates for the entity can we know why it's throwing a datastore contention and why it is not retrying. Do we need to explicitly handle?

**code**
<img width="572" alt="Screenshot 2019-12-26 at 12 32 38 PM" src="https://user-images.githubusercontent.com/34806853/71463225-af43d200-27db-11ea-8fe5-bfdc4b7d72ea.png">

**Comment by stickfigure** [comment]
The concurrency behavior of the datastore is fairly well documented. Objectify doesn't do anything special - if you're getting concurrency exceptions from the com.google.* layer, then study the datastore limitations? This question, I'm afraid, is too vague for me to do much with.
