### ISSUE TITLE
.cache(false) always reads from Global Cache

### ISSUE THREAD

**Issue by alysyk** [objectify/objectify#447]
After creating an Objectify via the ObjectifyFactory, if you try to use `Objectify#cache(false)`, the resulting Objectify will always read from the global cache.

It seems like the issue is in the `makeNew` method:

```java
	/** Same transactor, different options */
	private ObjectifyImpl makeNew(final ObjectifyOptions opts) {
		return makeNew(opts, ofy -> transactor);
	}
```

This is due to the one-arg constructor for ObjectifyImpl:
```java
	public ObjectifyImpl(final ObjectifyFactory fact) {
		this.factory = fact;
		this.options = new ObjectifyOptions();
		this.transactor = new TransactorNo(this);
	}
```

Since the new ObjectifyImpl is not passed in the `makeNew`, rather the Transactor is reused, it will reuse the original ObjectifyOptions which by default will use the global cache.

**Comment by stickfigure** [comment]
Wow, you're right. I will fix this asap.

**Comment by stickfigure** [comment]
Fixed in the next release

**Comment by alysyk** [comment]
Thanks! When are you expecting to release next?

**Comment by stickfigure** [comment]
Today... just trying to kill off one more issue in the backlog.

**Comment by alysyk** [comment]
Amazing! Thank you again!!
