### ISSUE TITLE
Import object with id, create new objects with automatic Id -> imported object is overwritten

### ISSUE THREAD

**Issue by Rhobal** [objectify/objectify#449]
The following test fails
The Entity "HasId" usually has autogenerated IDs which are incremented for each object.
However, when I import an Object with a predefined id and then save new objects with autopopulated (null) ids, the imported object will be overwritten once the autoincrement reaches the pre-used ID.

```java
	@com.googlecode.objectify.annotation.Entity
	private static class HasId {
		@Id Long id = null;
		
		public String toString() {return "hasId " + id;}
	}

	@Test
	void insertTest() throws Exception {
		factory().register(HasId.class);

		final HasId hi = new HasId();
		hi.id = 3L;

		final com.googlecode.objectify.Key<HasId> key = ofy().save().entity(hi).now();
		ofy().clear();
		HasId fetched = ofy().load().key(key).now();
		assertThat(fetched.id, is(hi.id));
		
		for(int i = 0; i < 100; i++) {
			final HasId hin = new HasId();
			ofy().save().entity(hin).now();

			final List<HasId> list = ofy().load().type(HasId.class).list();
			assertThat("Did not find hasi "+hin.id+" in " + list, list, Matchers.hasSize(i + 2));
		}		
	}
```

**Comment by stickfigure** [comment]
This is normal behavior for the datastore. You can't really mix and match chosen ids and allocated ids; you have to do one or the other. If you want quasi-chosen ids, you can allocate them using ObjectifyFactory.allocateIds (either one at a time, or as a block) - but you can't choose the numbers individually.
