### ISSUE TITLE
Problem using cursor on Objectify v5

### ISSUE THREAD

**Issue by UlisesCeca** [objectify/objectify#450]
I'm trying to use Cursors on Objectify v5 but when following the example I get an exception thrown.

My code:

```
import com.google.appengine.api.datastore.Cursor;
import com.google.appengine.api.datastore.QueryResultIterator;

Query<IndicadorEntity> query = ofy().load().type(IndicadorEntity.class).limit(1000);
query.startAt(Cursor.fromWebSafeString("1"));
final List<IndicadorEntity> indicadorEntities = new ArrayList<>();
QueryResultIterator<IndicadorEntity> iterator = query.iterator();

while (iterator.hasNext()) {
      indicadorEntities.add(iterator.next());
}
```

and I'm getting the following exception:

```
java.lang.IllegalArgumentException: Unable to decode provided cursor.
[INFO] GCLOUD: 	at com.google.appengine.api.datastore.Cursor.fromWebSafeString(Cursor.java:115)
```

Whatis wrong? I can't find any issue like this on Google and I just followed the example here.

Thanks.

**Comment by stickfigure** [comment]
As answered on SO:

`query.startAt(Cursor.fromWebSafeString("1"));`

is a no-op. Objectify's API uses a functional style and all returned API objects are immutable.

**Comment by UlisesCeca** [comment]
I don't understand why do you close this since it's not solved yet. How should I do it then? Nothing on SO worked for me
