### ISSUE TITLE
Race condition in SpyMemcacheService

### ISSUE THREAD

**Issue by vandebo2** [objectify/objectify#451]
It looks to me that this is a race condition in `SpyMemcacheService.getIdentifiable(final String key)`.

It tries to get an identifiable for the key and if they key isn't present, it adds the key with a default "null" value.  If the key is set between the first `gets` and the `set`, the value will be overwritten.

I think the fix is simple, change the `set` to an `add`. In the non-race case, the `add` will succeed and the method will operate as before.  If there is a race, the `add` will fail, but the subsequent `gets` will get the new identifiable instead.

**Comment by stickfigure** [comment]
Good catch!
