### ISSUE TITLE
Potential Memory Leak in Querying and Saving Entities in Datastore

### ISSUE THREAD

**Issue by deepfriedbrain** [objectify/objectify#455]
I'm using Objectify v5.1.21 with GAE Java SDK v1.9.76 for my application running on GAE. I do not use Memcache with Objectify (none of my entities have the `@Cached` annotation).

My application uses Google Cloud Endpoints 2.0 to serve requests from clients. All EndPoints classes and other servlets are defined as `@Singleton`. The server does not use Session cache and no references are held in memory after an Endpoint method completes serving a request.

I also using Guice for dependency injection.

The following 2 issues occur on the Production version (not my local env) of the app:

**Issue 1**

I have noticed that with each Objectify API call particularly to read entities, the memory footprint of the instance keeps growing. 

I have an Entity that has one particular property, which can potentially hold up to about 80-100KB of data. If a client requests for 20 of those entities (an average request would be for about 5 entities), the server instance memory usage grows by about 20MB with just a single datastore query of 20 such entities. If I repeat the query 5-10 times, I can see that the memory usage of the instance continues to grow by 20MB first, then 15MB for subsequent call, then another 10MB and so on until it stop growing at about the 10th call or so.

Is Objectify holding on to the references somewhere in memory? Here's how I do the queries typically. Am I doing anything wrong that would lead to a memory leak?

```
@Inject private static ModelDao modelDao;

//...

// Inside EndPoint method
MyEntity entityParams = new Entity();
entityParams.setEmailId("email_id_of_user");

List<Model> results = modelDao.listByExample(entityParams, "-date");

// Process results and return to the client
```

```
@Singleton
public class ModelDao extends ObjectifyDao<Model>{
    static {
        ObjectifyService.register(MyEntity.class);
        ...
    }
}
```

```
public abstract class ObjectifyDao<T> {
    //...
    public Key<T> put(T entity) {
        return ofy().save().entity(entity).now();
    }

    public List<T> listByExample(T exampleObj, String order) {
        Query<T> queryByExample = buildQueryByExample(exampleObj);
        return queryResults(queryByExample, order);
    }

    private List<T> queryResults(Query<T> queryByExample, String order) {
        List<T> results = null;

        if (order == null) {
            results = queryByExample.list();
        }
        else {
            results = queryByExample.order(order).list();
        }

        return asList(results);
    }

    private Query<T> buildQueryByExample(T exampleObj) {
        @SuppressWarnings("unchecked")
        Class<T> persistentClass = (Class<T>) exampleObj.getClass();
        Query<T> q = ofy().load().type(persistentClass);
    	return processQuery(exampleObj, q, persistentClass);
    }

    private List<T> asList(Iterable<T> iterable) {
        ArrayList<T> list = new ArrayList<T>();
        for (T t : iterable) {
            list.add(t);
        }
        return list;
    }
    //...
}
```

I have started using the Datastore Reflection APIs to only query specific properties of my Entity and I do not query the large property at all. This way I have managed to side step this issue.

**Issue 2** 

I have another case where I was trying to reindex objects of the same Entity type using Task Queues. All I do is the query the entities, and then save them back. The page size is set to 10. After about 65 iterations (650 entities), the job would run out of memory. Following is the full source code of the servlet.

Can someone explain why it would go Out of Memory when I'm querying and processing only 10 objects at a time, and not holding on to the references?

```
package com.mycompany.myproject.server.utils;

import static com.googlecode.objectify.ObjectifyService.ofy;

import java.io.IOException;
import java.util.logging.Logger;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.mycompany.myproject.models.MyEntity;
import com.google.appengine.api.datastore.Cursor;
import com.google.appengine.api.datastore.QueryResultIterator;
import com.google.appengine.api.taskqueue.DeferredTask;
import com.google.appengine.api.taskqueue.Queue;
import com.google.appengine.api.taskqueue.QueueFactory;
import com.google.appengine.api.taskqueue.TaskOptions;
import com.google.inject.Singleton;
import com.googlecode.objectify.cmd.Query;

@Singleton
public class IndexingServlet extends HttpServlet {

    private static final Logger logger = Logger.getLogger(IndexingServlet.class.getName());

    public static class IndexObjects implements DeferredTask {

        private static final int DATASTORE_PAGE_SIZE = 10;

        @Override
        public void run() {
            String cursorString = "";
            int count = 0;
            int maxCount = 70;
            while (count < maxCount) {
                count++;

                Query<MyEntity> query = ofy().load().type(MyEntity.class).order("-date").limit(DATASTORE_PAGE_SIZE);

                if (cursorString != null) {
                    query = query.startAt(Cursor.fromWebSafeString(cursorString));
                }

                QueryResultIterator<MyEntity> iterator = query.iterator();

                while (iterator.hasNext()) {
                    MyEntity myEntity = iterator.next();
                    ofy().save().entity(myEntity).now();
                    cursorString = iterator.getCursor().toWebSafeString();
                }
            }
        }
    }

    @Override
    public void doGet(HttpServletRequest request, HttpServletResponse response)
        throws ServletException, IOException {
        Queue queue = QueueFactory.getDefaultQueue();
        queue.add(TaskOptions.Builder.withPayload(new IndexObjects()));
        return;
    }
}
```

Here's the OutOfMemory error from the above Servlet:

```
com.google.apphosting.runtime.jetty9.JettyLogger warn: Error for /_ah/queue/__deferred__ (JettyLogger.java:29)
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOf(Arrays.java:3236)
	at com.google.io.protocol.ProtocolSink.toArray(ProtocolSink.java:90)
	at com.google.io.protocol.ProtocolMessage.toByteArray(ProtocolMessage.java:357)
	at com.google.apphosting.runtime.http.HttpApiHostClient.call(HttpApiHostClient.java:243)
	at com.google.apphosting.runtime.ApiProxyImpl.finishAsyncApiCallSetup(ApiProxyImpl.java:443)
	at com.google.apphosting.runtime.ApiProxyImpl.doAsyncCall(ApiProxyImpl.java:398)
	at com.google.apphosting.runtime.ApiProxyImpl.lambda$makeAsyncCall$1(ApiProxyImpl.java:242)
	at com.google.apphosting.runtime.ApiProxyImpl$$Lambda$26/1625823299.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.google.apphosting.runtime.ApiProxyImpl.makeAsyncCall(ApiProxyImpl.java:241)
	at com.google.apphosting.runtime.ApiProxyImpl.makeAsyncCall(ApiProxyImpl.java:66)
	at com.google.apphosting.api.ApiProxy.makeAsyncCall(ApiProxy.java:210)
	at com.google.appengine.api.datastore.DatastoreApiHelper.makeAsyncCall(DatastoreApiHelper.java:111)
	at com.google.appengine.api.datastore.AsyncDatastoreServiceImpl$4.makeCall(AsyncDatastoreServiceImpl.java:180)
	at com.google.appengine.api.datastore.AsyncDatastoreServiceImpl$4.makeCall(AsyncDatastoreServiceImpl.java:162)
	at com.google.appengine.api.datastore.BaseAsyncDatastoreServiceImpl$BaseRpcBatcher.makeCalls(BaseAsyncDatastoreServiceImpl.java:80)
	at com.google.appengine.api.datastore.AsyncDatastoreServiceImpl.doBatchPut(AsyncDatastoreServiceImpl.java:430)
	at com.google.appengine.api.datastore.BaseAsyncDatastoreServiceImpl.put(BaseAsyncDatastoreServiceImpl.java:262)
	at com.googlecode.objectify.impl.WriteEngine.save(WriteEngine.java:87)
	at com.googlecode.objectify.impl.SaverImpl.entities(SaverImpl.java:60)
	at com.googlecode.objectify.impl.SaverImpl.entity(SaverImpl.java:35)
	at com.mycompany.myproject.server.utils.IndexingServlet$IndexObjects.run(IndexingServlet.java:144)
	at com.google.apphosting.utils.servlet.DeferredTaskServlet.performRequest(DeferredTaskServlet.java:142)
	at com.google.apphosting.utils.servlet.DeferredTaskServlet.service(DeferredTaskServlet.java:101)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1772)
	at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:48)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)

```

In both the cases above, it seems like there's some memory leak taking place, but I cannot pinpoint the root cause.

**Comment by stickfigure** [comment]
You are almost certainly seeing the session cache:

https://github.com/objectify/objectify/wiki/Caching

If you iterate through large numbers of entities (eg, your indexing servlet), you should set a batch size N and then clear() the cache every N iterations. Incidentally, that's not a transactionally safe operation - the safe way to reindex lots of entities is to enqueue one task per entity, and each task does a load+save in a transaction.

If you're filling the cache through normal operation, I have other questions - do you have normal work boundaries or is this some sort of long-running operation? If you have long-running operations, you may have to clear the session. But long-running sessions are an unusual use case.

**Comment by deepfriedbrain** [comment]
@stickfigure Thanks for your response. 

What you said for the second issue makes sense to me. It was a one-off requirement to reindex the items. I'll use your suggestion if I have to do such an activity again in the future.

The normal operations are simple requests to EndPoint APIs that usually complete within 1 sec for 90% of the requests. There are some requests that may take up to 2 secs to complete, but that's about the most it would take for any request in my app. So I don't have any long running operations and I don't use task queues in normal operations.

As I described in the OP, I have a particular Entity that has one property which can hold up to 80-100KB of information. Querying 20 objects of this Entity causes the application's memory usage to go up with each request. I reproduced the problem and managed to push up the memory by about 80 MB by simply repeating the same request about 10-12 times.

I realized that I didn't actually need to query that large property at all. What I really needed was a **projection query** to get all the other properties except that large property. I couldn't easily find the documentation on how to achieve it with Objectify but I found the native datastore projection query API documentation.

After applying projection query yesterday, those 20 objects generate a total payload of just about 2 KB! So the main issue is pretty much resolved, but I'm still concerned that the memory usage builds up overtime for other queries. I'm not holding any references from any requests.

**Questions:**

1. I read through the Cache documentation but still not clear on one point. Does the session cache persist from one request to another? In other words, if I run the same query again as part of another request, do I get cached entities or entities from the datastore?

2. Is there any reason for me to use `clear()` for normal operations?

3. I have many normal operations where I query an entity, update its properties and `save()` it (all within about 0.5s). Should this be done in.a transaction? 

4. Can you point me to the documentation for projection queries with Objectify? I have seen `.project()` in some forums, but I couldn't find it in the official Wiki.

**Comment by stickfigure** [comment]
A bit late, but here are the answers for historical reference:

1. Session caches should not persist beyond a single request. They represent a (brief) session of work.
2. clear() is only to avoid OOME issues when you iterate through _lots_ of entities. You generally should not use it.
3. If you load an entity, change part of it, and save it - you need a transaction.
4. The only documentation for projection queries is the javadocs. This is a rather advanced feature for performance optimization and if you aren't sure how to use it, you probably don't want it.
