### ISSUE TITLE
Data reverting back to previous state

### ISSUE THREAD

**Issue by krishnagangula** [objectify/objectify#463]
We are facing data loss issue from the past few weeks. The records are saved properly in the datastore. After a few days, some records revert back to the previous state. We have a background job called ReSaveCase, which gets the data directly from the datastore and resaves it. At this point of resaving, some data is reverting back to the previous state. We are not sure from where this previous state is coming from as we are directly getting the data from datastore itself. We are using Objectify to perform operations on datastore.

This ReSaveCase method gets all the updated cases(CaseDO entity in datastore) in the last 24 hours and then resaves it. When it resaves some of the cases are reverting back to the previous state which means all the changes done in this 24 hours are gone. 

Steps involved in ReSaveCase process:
- Getting data from datastore using Objectify (ofy().load().type(CaseDO.class).id(caseId).now()).
- Updating invoiceStatus, caseCategory, internalStatusChangeDate and caseSearchIndexTokens properties in the caseDO entity based on some conditions.
- Saving the data using Objectify (ofy().save().entity(caseDO).now()).

**Background job triggering point**
`

    Queue queue = QueueFactory.getDefaultQueue();
    DatastoreService ds = DatastoreServiceFactory.getDatastoreService();
    String backendAddress = BackendServiceFactory.getBackendService().getBackendAddress("memdb");
    TaskOptions task =
      TaskOptions.Builder.withUrl("/indexcase").param("caseStatusId", caseStatusId.toString())
          .param("indexAll", "1").method(Method.GET).header("Host", backendAddress);
    Transaction txn = ds.beginTransaction();
    queue.add(task);
    txn.commit();
`

**Background job**
`

     CaseDO caseDO = ofy().load().type(CaseDO.class).id(caseId).now();
     if (caseInvStatus != null) {
        caseDO.updateCaseInoiceStatus(caseInvStatus.name());
        logger.log(Level.INFO, "CaseDO after updating case invoice status {0}", caseDO);
      }
     // Add category to case according to case status.
     if (caseDO.getCaseStatus() != null) {
       Ref<CaseStatusDO> refCaseStatus = caseDO.getCaseStatus();
       CaseStatusDO caseStatusDO = refCaseStatus.get();
       if (caseStatusDO != null) {
         Ref<CaseCategoryDO> refCaseCategory = caseStatusDO.getCaseCategory();
         // Add the reference to the category only for indexing/search purposes.
         caseDO = CaseDO.getBuilder(caseDO).withCaseCategory(refCaseCategory).build();
       }
     }
     // Initialise the internal status change date which is used for sorting on internalStatusChangeDate.
     // caseDO.initCaseInternalStatus();
     if(internalStatus != null) {
       if (!Strings.isNullOrEmpty(internalStatus.getStatusMsg())) {
         internalStatusChangeDate = internalStatus.getDate();
       } else {
         internalStatusChangeDate = null;
       }
     }
     // Generates search indexes for 12 fields in one indexed field.
     caseDO.processSearchIndexes();
     ofy().save().entity(caseDO).now();
`
We are maintaining logs which keeps the track on any operations done on the entity.

In the below screenshots, Case status was updated to "Spec Cases PD current" on 09/25/2020. But, it got reverted back to "Spec Cases 1-140 App Waiting".
![CaseDataLossScreenshots](https://user-images.githubusercontent.com/72606660/96476152-83a24480-1252-11eb-9894-b1f4752ba22f.png)

**Comment by stickfigure** [comment]
Going through old issues.

This can't possibly be related to anything that Objectify does. Objectify just loads and saves some data using lower-level APIs, and assembles/disassembles POJOs. If your data is changing days later, this is not something Objectify can do. 

At a total wild guess, maybe you have data sitting in a task queue that is overwriting your current data?
