### ISSUE TITLE
ObjectifyFilter and Ktor

### ISSUE THREAD

**Issue by Burtan** [objectify/objectify#471]
Are there any examples?
I just found this on stackoverflow and it looks suboptimal.

"The Problem is that ktor uses coroutines. Coroutines run in a thread pool by default and the ObjectifyFilter is only active for the thread receiving the request. I use this workaround until I find something better:
```
get(path) {
    withContext(Dispatchers.Unconfined) {
        val content = page.doGet()
        call.respond(content)
    }
}
```

The Unconfined dispatcher runs the coroutine in the same thread who started it, at least until the first suspend."

**Comment by bcwhite-code** [comment]
I found that same SO article looking at the same problem... but it's about JUnit, not http requests.  The stated solution didn't help me.

I'm sure I'm missing something in the `embeddedServer` definition or some external config file that sets up an appropriate ObjectifyFilter.

**Comment by stickfigure** [comment]
Don't forget that try-with-resources calls `close()` on the returned object. So, do a `try/finally/close`.
