### ISSUE TITLE
Testing best practice for JDK 11/Appengine JDK 11

### ISSUE THREAD

**Issue by Burtan** [objectify/objectify#474]
Hey,
updating to Appengine with JDK 11 involves lots of framework transitions. Part of it is the deprecation of all appengine testing classes. Looking into the source of objectify those packages are not used, however LocalDatastoreHelper from the google cloud datastore package is used. However, this class is annotated as InternalApi, so I wonder what is currently the best practice to write Objectify/Datastore tests.

**Comment by stickfigure** [comment]
I just use the LocalDatastoreHelper. My test harnesses look pretty similar to the Objectify test harness, with Junit5 extensions. It's what I would recommend.
