### ISSUE TITLE
Objectify V6.0.7 with GAE Standard: toUrlSafe result cannot back to valid Key

### ISSUE THREAD

**Issue by July-G** [objectify/objectify#477]
I'm using Objectify V6 with GAE Standard,  code as below:

> String mykey = ofy().save.entity(xxx).now().toUrlSafe();
> ofy().load().key(Key.create(mykey)).now() produce null result

Please advice. Thanks.

**Comment by stickfigure** [comment]
I'm not quite sure what to say. I just added a test that looks pretty much exactly like this and it seems to work.

If you can explain in more detail, I can reopen this
