### ISSUE TITLE
String ID's do not get generated on save

### ISSUE THREAD

**Issue by bogdan-marian** [objectify/objectify#482]
In case you would like to use strings as id it seems that Objectify 6 does not autogenerate them anymore 
```
@Entity
public class Car {
    @Id
    public String id; //this throws Cannot save an entity with a null String @Id:
}

@Entity
public class Car {
    @Id
    public Long id; //this works
}

// persist a new car
Car porche = new Car();
ofy().save().entity(porche).now();
```
This works in objectify:5 but doesn't not in objectify:6. Was the support for automatically generated string ID's dropped in objectify 6? 
How do you persist new objects with string id's in objectify 6?

**Comment by stickfigure** [comment]
Strings have never autogenerated ids, not with 6 or 5 or any previous version.

**Comment by stickfigure** [comment]
If you want to autogenerate string ids... Use a uuid? Use the allocator and stringify the number? Seems like there are lots of ways, up to you. But personally if I am generating ids I use a Long type.

**Comment by bogdan-marian** [comment]
Thank you so much for this. I just got dropped into a project that uses v5 where id's seemed that they are generated automatically but they are not. Your answer pointed me to dig deeper into how the Id's are generated for this project. Is a very custom in-house solution that is also not safe. There is a risk of collision. Using the allocator and stringify'ing the number seams like a good fix. 

@stickfigure  Will this guarantee that I will never get collisions? 

```
 Key<Car> carKey = new ObjectifyFactory().allocateId(Car.class);
porche.id = String.valueOf(carKey.getId());
```

**Comment by stickfigure** [comment]
@bogdan-marian You couldn't create an ObjectifyFactory like that, but if you use the `ObjectifyFactory.allocateId` method, you will not have collisions. `ObjectifyService.factory()` should get you the relevant factory.

Personally I never use the save-creates-the-id approach and always explicitly allocate ids. I don't like having entities with null ids, it creates all sorts of problems. Allocate the id when you construct the new entity, then save it.

**Comment by bogdan-marian** [comment]
Thanks. 
```
Key<Car> carKey = ObjectifyService.factory().allocateId(Car.class);
porche.id = String.valueOf(carKey.getId());
```
I tested with this and it works.
