### ISSUE TITLE
GWT support

### ISSUE THREAD

**Issue by mahmoudzaki12000** [objectify/objectify#484]
we are facing issue with serialization in gwt client side with new key and cloud datastore key. old key and objectify-gwt jar was fixing this but now it does not work.  old key was having  com.google.appengine.api.datastore.Key but new key has com.google.cloud.datastore.Key. So if we can fix this it will help us to continue use objectify.

**Comment by stickfigure** [comment]
This is really a question for the objectify-gwt project. Let's keep that discussion here:
https://github.com/objectify/objectify-gwt/issues/5
