### ISSUE TITLE
Support Java14 Record classes for Entity

### ISSUE THREAD

**Issue by anantdamle** [objectify/objectify#487]
With Java 17 now LTS, record classes are much more used for data interchange and hand-crafter DTO objects.

Add support for record class to be annotated as `@Entity`

e.g.
```java
@Entity
public record MyEntity(@Id String id, String name) {}
```

**Comment by nicolascwp** [comment]
Record fields are final, causing this error:

`final field has no write access: MyClass.name/java.lang.String/putField, from class com.googlecode.objectify.impl.FieldProperty`

**Comment by anantdamle** [comment]
Understand, My initial thought was if it was possible to modify the underlying member field.
Though that seems not possible as the underlying member field is declared as final.
