### ISSUE TITLE
Objectify v6.0.8+ Incompatible With google-api-services-drive

### ISSUE THREAD

**Issue by bcwhite-code** [objectify/objectify#489]
This is actually a problem with the Drive API library described here:
https://issuetracker.google.com/issues/268844492

I'm mentioning in the Objectify issue tracking on the hope that someone with connections inside Google can bring it up with the Drive team and get it fixed.

**Comment by stickfigure** [comment]
I see a package: pkg:maven/com.google.apis/google-api-services-drive@v3-rev20230212-2.0.0

The -2.0.0 at the end means it's compatible with the v2 google api client. Why not use that?

**Comment by bcwhite-code** [comment]
Because I never came across it!  <clickity click>

Oh!  It's _later_ in the sort order on MvnRepository:
https://mvnrepository.com/artifact/com.google.apis/google-api-services-drive

You have to go about 1/3 down the (very long) page to find it.  Thank you for that!

**Comment by stickfigure** [comment]
No problem, glad you're back in business!
