### ISSUE TITLE
Ref<?> NotSerializableException after upgrading from 6.0.9 to 6.1.0

### ISSUE THREAD

**Issue by Khidala** [objectify/objectify#501]
After upgrading Objectify from 6.0.9 to 6.1.0, I am seeing lots of errors without much stack trace; I just see this on Google App Engine:
java.io.NotSerializableException: com.googlecode.objectify.Ref

Based on release notes, Ref<?> is no longer serializable, so most likely I am encountering what was noted for Ref<?>.

Reference:
[https://github.com/objectify/objectify/wiki/UpgradeVersion6ToVersion61#ref-is-no-longer-serializable]

I have lots of classes/objects using Ref<?> using @Load: e.g.:
```
@Load
private Ref<Animal> animalRef;
```
Is it possible to make it backward-compatible in any way? Thanks.

**Comment by Khidala** [comment]
I see what you are saying and it makes sense. Let me see how I can avoid serializing Ref<?> fields, one option is to mark them transient. Since there are a lot of classes making use of Ref, it is a non-trivial change. I am not pressed to get to Objectify v6.1, so you don't have to investigate making it work. Will certainly reach out if I need any recommendations, thanks for your response!

**Comment by stickfigure** [comment]
Great - if you hit any further snags, post here and we'll re-open the issue.
