### ISSUE TITLE
Retries not working properly with latest Datastore SDK / Firestore Emulator

### ISSUE THREAD

**Issue by kevin-wise** [objectify/objectify#510]
In TransactorNo, it's checking for `ex.getMessage().contains("transaction closed")`, but the latest Datastore SDK has a message of "Transaction is invalid or closed." (at least, using the latest Firestore emulator). So the exception doesn't get handled like it used to, causing retries to work improperly.  The exception "Failed retrying datastore..." never happens

**Comment by stickfigure** [comment]
PR merged, thanks!
